import test from "node:test";import assert from "node:assert/strict";
import {createPartyState} from "../src/domain/state.js";
import {addRecipeToMenu,requiredServingsForDish,deriveBatchPlanForDish} from "../src/domain/recipes.js";
import {deriveShoppingList} from "../src/domain/shopping.js";
import {derivePrepTasks} from "../src/domain/prep.js";
import {deriveTurkeyPlan} from "../src/domain/turkey.js";
import {deriveEquipmentPlan} from "../src/domain/equipment.js";
import {deriveTimeline} from "../src/domain/schedule.js";
import {deriveDietaryCoverage,deriveMenuCompleteness} from "../src/domain/coverage.js";
import {upsertRecipe} from "../src/domain/recipes.js";
import {derivePlan} from "../src/domain/planning.js";

test("role-share divides a shared meal role",()=>{let s=createPartyState({planning:{mode:"estimated",estimatedHeadcount:18,roleServingTargets:{starch:1}}});for(const id of ["mash","stuffing","mac"])s=addRecipeToMenu(s,{id,title:id,mealRole:"starch",baseServings:6,servingStrategy:{basis:"role-share"},ingredients:[]});assert.equal(requiredServingsForDish(s,"mash"),6);s={...s,dishes:{...s.dishes,mac:{...s.dishes.mac,roleShareWeight:2}}};assert.equal(requiredServingsForDish(s,"mac"),9);assert.equal(requiredServingsForDish(s,"mash"),4.5);});

test("batch capacity creates sequential waves only when capacity is exceeded",()=>{let s=createPartyState({planning:{mode:"estimated",estimatedHeadcount:24}});s=addRecipeToMenu(s,{id:"casserole",title:"Casserole",baseServings:8,batchCapacityServings:8,parallelBatchCapacity:1,prepTasks:[{id:"cook",title:"Bake",phase:"cook",durationMinutes:40,batchable:true}],ingredients:[]});assert.deepEqual({...deriveBatchPlanForDish(s,"casserole"),requiredServings:24},{dishId:"casserole",requiredServings:24,batches:3,parallelCapacity:1,waves:3,capacityKnown:true});assert.equal(derivePrepTasks(s).find(x=>x.dishId==="casserole").durationMinutes,120);});

test("equipment gaps flow into hosting-supply shopping",()=>{let s=createPartyState({inventory:{"large-bowl":1}});s=addRecipeToMenu(s,{id:"mash",title:"Mash",baseServings:12,equipment:[{id:"pot",name:"Large pot",quantity:1}],servingRequirements:[{id:"large-bowl",name:"Large serving bowl",quantity:2}],ingredients:[]});const e=deriveEquipmentPlan(s);assert.equal(e.find(x=>x.key==="large-bowl").missing,1);assert.equal(deriveShoppingList(s).find(x=>x.key==="equipment:large-bowl").stillNeed.quantity,1);});

test("confirmed guest contribution keeps receive and serve tasks",()=>{let s=createPartyState();s=addRecipeToMenu(s,{id:"pie",title:"Pie",baseServings:8,ingredients:[],prepTasks:[{id:"bake",title:"Bake",phase:"cook",durationMinutes:45},{id:"receive",title:"Receive pie",phase:"receive",durationMinutes:5},{id:"serve",title:"Serve",phase:"serve",durationMinutes:5}]});s={...s,guests:[{guestId:"supplier",name:"Supplier",rsvp:"yes"}],menuResponsibilities:{pie:{ownerType:"guest",contributorGuestId:"supplier",status:"confirmed"}}};assert.deepEqual(derivePrepTasks(s).filter(x=>x.dishId==="pie").map(x=>x.title),["Receive pie","Serve"]);});

test("one oven separates flexible incompatible temperatures",()=>{let s=createPartyState({event:{dinnerAt:"2026-11-26T17:30:00-08:00",ovens:1,burners:4}});s=addRecipeToMenu(s,{id:"a",title:"A",baseServings:12,ingredients:[],prepTasks:[{id:"cook",title:"A bake",phase:"cook",durationMinutes:45,resourceRequirements:[{type:"oven",temperatureF:350}]}]});s=addRecipeToMenu(s,{id:"b",title:"B",baseServings:12,ingredients:[],prepTasks:[{id:"cook",title:"B bake",phase:"cook",durationMinutes:30,resourceRequirements:[{type:"oven",temperatureF:425}]}]});const t=deriveTimeline(s);assert.equal(t.issues.some(x=>x.type==="resource-conflict"),false);const [a,b]=t.tasks;assert.ok(a.end<=b.start||b.end<=a.start);});

test("fixed incompatible oven tasks report a conflict",()=>{let s=createPartyState({event:{dinnerAt:"2026-11-26T17:30:00-08:00",ovens:1}});s=addRecipeToMenu(s,{id:"a",title:"A",baseServings:12,ingredients:[],prepTasks:[{id:"cook",title:"A",phase:"cook",durationMinutes:45,fixedStart:"2026-11-26T16:00:00-08:00",resourceRequirements:[{type:"oven",temperatureF:350}]}]});s=addRecipeToMenu(s,{id:"b",title:"B",baseServings:12,ingredients:[],prepTasks:[{id:"cook",title:"B",phase:"cook",durationMinutes:45,fixedStart:"2026-11-26T16:15:00-08:00",resourceRequirements:[{type:"oven",temperatureF:425}]}]});assert.equal(deriveTimeline(s).issues.some(x=>x.type==="resource-conflict"),true);});

test("dinner-time change moves relative tasks but not fixed absolute tasks",()=>{let s=createPartyState({event:{dinnerAt:"2026-11-26T16:30:00-08:00"}});s=addRecipeToMenu(s,{id:"a",title:"A",baseServings:12,ingredients:[],prepTasks:[{id:"prep",title:"Prep",durationMinutes:30,finishOffsetMinutes:-60},{id:"pinned",title:"Pinned",durationMinutes:15,fixedStart:"2026-11-26T14:00:00-08:00"}]});let t=deriveTimeline(s);const r1=t.tasks.find(x=>x.title==="Prep").startAt,p1=t.tasks.find(x=>x.title==="Pinned").startAt;s={...s,event:{...s.event,dinnerAt:"2026-11-26T17:30:00-08:00"}};t=deriveTimeline(s);assert.notEqual(r1,t.tasks.find(x=>x.title==="Prep").startAt);assert.equal(p1,t.tasks.find(x=>x.title==="Pinned").startAt);});

test("turkey sizing changes while purchased weight remains committed",()=>{let s=createPartyState({planning:{mode:"estimated",estimatedHeadcount:18},turkeyPlan:{poundsPerPerson:1.25,purchasedWeightLb:24}});s=addRecipeToMenu(s,{id:"turkey",title:"Turkey",isTurkey:true,turkeyRules:{poundsPerPerson:1.25,thawHoursPerPound:6,cookMinutesPerPound:13},baseServings:18,ingredients:[]});let t=deriveTurkeyPlan(s);assert.equal(t.requiredWeightLb,22.5);assert.equal(t.surplusLb,1.5);s={...s,planning:{...s.planning,estimatedHeadcount:20}};t=deriveTurkeyPlan(s);assert.equal(t.requiredWeightLb,25);assert.equal(t.stillNeedLb,1);assert.equal(t.purchasedWeightLb,24);});

test("menu completeness and person-level dietary coverage react to current menu",()=>{let s=createPartyState({planning:{mode:"confirmed",requiredMenuRoles:["main","starch"],dietaryRequiredRoles:["main"]},guests:[{id:"maya",name:"Maya",rsvp:"yes",dietaryRestrictions:["vegetarian"]}]});s=addRecipeToMenu(s,{id:"turkey",title:"Turkey",mealRole:"main",metadataReviewed:true,dietaryTags:[],allergenReviewed:true,baseServings:12,ingredients:[]});assert.deepEqual(deriveMenuCompleteness(s).missing,["starch"]);assert.equal(deriveDietaryCoverage(s).gaps[0].status,"missing");s=addRecipeToMenu(s,{id:"veg",title:"Veg Main",mealRole:"main",metadataReviewed:false,dietaryTags:["vegetarian"],baseServings:4,ingredients:[]});assert.equal(deriveDietaryCoverage(s).gaps[0].status,"unresolved");s=upsertRecipe(s,{...s.recipes.veg,metadataReviewed:true,allergenReviewed:true});assert.equal(deriveDietaryCoverage(s).covered,true);});

test("derivePlan exposes connected cooking intelligence",()=>{let s=createPartyState({event:{dinnerAt:"2026-11-26T17:30:00-08:00"}});s=addRecipeToMenu(s,{id:"mash",title:"Mash",mealRole:"starch",baseServings:12,ingredients:[],prepTasks:[{id:"cook",title:"Cook",phase:"cook",durationMinutes:20,resourceRequirements:[{type:"burner"}]}]});const p=derivePlan(s);for(const k of ["timeline","equipment","menu","dietaryCoverage","turkey"])assert.ok(p[k]);});
