import {dishRequirementMode,normalizeDishRecord} from "./menu.js";
import {deriveBatchPlanForDish,recipeForDish} from "./recipes.js";
import {deriveServicePlan} from "./service.js";
import {deriveExperiencePlan} from "./experience.js";
import {deriveTurkeyPlan} from "./turkey.js";
import {deriveHousePrepTasks} from "./house.js";
const SERVICE_PHASES=new Set(["receive","reheat","finish","serve","hold"]);
function taskApplies(task,mode){if(Array.isArray(task.appliesTo))return task.appliesTo.includes(mode)||task.appliesTo.includes("any");if(mode==="homemade")return true;return SERVICE_PHASES.has(task.phase);}
function applyOverride(task,override={}){return {...task,...override,title:override.title??task.title,durationMinutes:override.durationMinutes==null?task.durationMinutes:Math.max(0,Number(override.durationMinutes)||0),completed:override.completed??task.completed};}
export function derivePrepTasks(state){const tasks=[];const turkeyPlan=deriveTurkeyPlan(state);if(turkeyPlan.dishId&&turkeyPlan.thawHours){const thawTaskId=`${turkeyPlan.dishId}:thaw-start`;tasks.push({id:thawTaskId,taskId:thawTaskId,title:`Move ${turkeyPlan.birdCount} turkey${turkeyPlan.birdCount===1?"":"s"} to refrigerator to thaw`,phase:"days-ahead",durationMinutes:5,handsOn:true,fixedStartOffsetMinutes:-Math.ceil(turkeyPlan.thawHours*60+1800),dishId:turkeyPlan.dishId,recipeTitle:turkeyPlan.recipeTitle,derived:true,source:"turkey-plan",detail:`${turkeyPlan.birdCount} bird${turkeyPlan.birdCount===1?"":"s"} · about ${turkeyPlan.averageBirdWeightLb.toFixed(1)} lb each`});}for(const [dishId,dishRaw] of Object.entries(state.dishes||{})){if(!dishRaw?.on)continue;const dish=normalizeDishRecord(dishRaw),recipe=recipeForDish(state,dishId);if(!recipe)continue;const requirementMode=dishRequirementMode(dishId,state),mode=requirementMode==="ingredients"?"homemade":requirementMode==="prepared-food"?"purchased":"guest-provided",batch=deriveBatchPlanForDish(state,dishId);for(const task of recipe.prepTasks){if(!taskApplies(task,mode))continue;const taskId=`${dishId}:${task.id}`,dependsOn=(task.dependsOn||[]).map(id=>id.startsWith(`${dishId}:`)?id:`${dishId}:${id}`);let durationMinutes=task.dynamicDuration==="turkey-roast"&&turkeyPlan.dishId===dishId?turkeyPlan.cookMinutes:task.durationMinutes;if(task.phase==="cook"&&batch?.waves>1&&task.batchable!==false)durationMinutes*=batch.waves;const base={...task,taskId,id:taskId,dependsOn,dishId,recipeId:recipe.id,recipeTitle:recipe.title,preparationMode:mode,durationMinutes,derived:true,batchWaves:task.phase==="cook"?batch?.waves||1:1};tasks.push(applyOverride(base,state.taskOverrides?.[taskId]));}}
 for(const task of deriveHousePrepTasks(state)){const id=task.taskId||task.id;tasks.push(applyOverride({...task,taskId:id},state.taskOverrides?.[id]));}
 for(const task of deriveServicePlan(state).tasks){const id=task.taskId||task.id;tasks.push(applyOverride({...task,taskId:id},state.taskOverrides?.[id]));}
 for(const task of deriveExperiencePlan(state).tasks){const id=task.taskId||task.id;tasks.push(applyOverride({...task,taskId:id},state.taskOverrides?.[id]));}
 for(const manual of state.manualTasks||[])tasks.push({...manual,taskId:String(manual.taskId||manual.id),id:String(manual.taskId||manual.id),manual:true,derived:false,dependsOn:Array.isArray(manual.dependsOn)?manual.dependsOn:[],durationMinutes:Math.max(0,Number(manual.durationMinutes)||0),resourceRequirements:Array.isArray(manual.resourceRequirements)?manual.resourceRequirements:[]});
 return tasks;}
