import {derivePrepTasks} from "./prep.js";import {kitchenResources} from "./kitchen.js";import {recipeForDish} from "./recipes.js";import {deriveTurkeyPlan} from "./turkey.js";
const MINUTE=60000;
const overlaps=(a,b)=>a.start<b.end&&b.start<a.end;
function anchorMinutes(state){const value=state.event?.dinnerAt;const ms=value?Date.parse(value):NaN;return Number.isFinite(ms)?ms/MINUTE:0;}
function topo(tasks){const byId=new Map(tasks.map(t=>[t.taskId,t]));const indegree=new Map(tasks.map(t=>[t.taskId,0]));const next=new Map(tasks.map(t=>[t.taskId,[]]));for(const t of tasks)for(const dep of t.dependsOn||[]){if(!byId.has(dep))continue;indegree.set(t.taskId,(indegree.get(t.taskId)||0)+1);next.get(dep).push(t.taskId);}const q=[...indegree].filter(([,d])=>d===0).map(([id])=>id),order=[];while(q.length){const id=q.shift();order.push(id);for(const n of next.get(id)||[]){indegree.set(n,indegree.get(n)-1);if(indegree.get(n)===0)q.push(n);}}return {order,cycle:order.length!==tasks.length,next,byId};}
function normalizedRequirements(task){const req=[...(task.resourceRequirements||[])];if(task.handsOn&&!req.some(r=>(r.type||r.resourceType)==="host"))req.push({type:"host",slots:1});return req.map(r=>({...r,type:r.type||r.resourceType,slots:Math.max(1,Number(r.slots)||1)})).filter(r=>r.type);}
function canUse(resource,req,start,end,reservations){const relevant=reservations.filter(x=>x.resourceId===resource.id&&overlaps({start,end},x));if(resource.type==="oven"&&req.temperatureF!=null){for(const x of relevant)if(x.temperatureF!=null&&Number(x.temperatureF)!==Number(req.temperatureF))return false;}const used=relevant.reduce((n,x)=>n+(x.slots||1),0);return used+req.slots<=resource.capacitySlots;}
function findPlacement(reqs,start,end,resources,reservations,fixed){if(!reqs.length)return {start,end,assignments:[]};let s=start,e=end;for(let attempt=0;attempt<500;attempt++){const assignments=[];let blockerEnd=null;let ok=true;for(const req of reqs){const candidates=resources.filter(r=>r.type===req.type);let chosen=null;for(const resource of candidates)if(canUse(resource,req,s,e,reservations)){chosen=resource;break;}if(!chosen){ok=false;for(const resource of candidates){for(const x of reservations.filter(x=>x.resourceId===resource.id&&overlaps({start:s,end:e},x)))blockerEnd=blockerEnd==null?x.start:Math.min(blockerEnd,x.start);}break;}assignments.push({resourceId:chosen.id,...req});}if(ok)return {start:s,end:e,assignments};if(fixed||blockerEnd==null)return null;e=blockerEnd;s=e-(end-start);}return null;}
export function deriveTimeline(state){const tasks=derivePrepTasks(state).filter(t=>t.durationMinutes>0||t.fixedStart||t.fixedStartOffsetMinutes!=null||t.finishOffsetMinutes!=null);const graph=topo(tasks);const issues=[];const turkey=deriveTurkeyPlan(state);for(const code of turkey.issues||[]){if(code==="turkey-oven-capacity-review")issues.push({type:"capacity-review",resource:"oven",title:"Turkey plan needs multiple oven waves",explanation:`${turkey.birdCount} birds require ${turkey.ovenWaves} oven waves with ${turkey.ovenCount} oven${turkey.ovenCount===1?"":"s"}.`,recommendation:"Add oven capacity, use prepared turkey, reduce the bird count, or plan staggered roasting and safe holding."});else issues.push({type:code,title:"Turkey plan needs review"});}for(const [dishId,dish] of Object.entries(state.dishes||{})){if(!dish?.on)continue;const recipe=recipeForDish(state,dishId);if(recipe?.recipeComplete===false)issues.push({type:"recipe-incomplete",dishId,title:recipe.title,reason:"Full method, dependencies and resource requirements have not been reviewed"});}if(graph.cycle)issues.push({type:"dependency-cycle"});const anchor=anchorMinutes(state),resources=kitchenResources(state),reservations=[],scheduled=new Map();const dependents=graph.next;
 for(const id of [...graph.order].reverse()){const task=graph.byId.get(id);const duration=Math.max(0,Number(task.durationMinutes)||0);const childStarts=(dependents.get(id)||[]).map(x=>scheduled.get(x)?.start).filter(Number.isFinite);let latestEnd=childStarts.length?Math.min(...childStarts):anchor;if(task.finishOffsetMinutes!=null)latestEnd=Math.min(latestEnd,anchor+Number(task.finishOffsetMinutes));const fixedAbsolute=task.fixedStart?Date.parse(task.fixedStart)/MINUTE:NaN;const fixedOffset=task.fixedStartOffsetMinutes!=null?anchor+Number(task.fixedStartOffsetMinutes):NaN;const fixedStart=Number.isFinite(fixedAbsolute)?fixedAbsolute:Number.isFinite(fixedOffset)?fixedOffset:null;let start=fixedStart??latestEnd-duration,end=(fixedStart??latestEnd-duration)+duration;const reqs=normalizedRequirements(task);const placed=findPlacement(reqs,start,end,resources,reservations,fixedStart!=null||task.movableEarlier===false);if(!placed){scheduled.set(id,{...task,start,end,assignments:[],conflict:true});issues.push({type:"resource-conflict",taskId:id,requirements:reqs});continue;}start=placed.start;end=placed.end;const latestDependencyStart=childStarts.length?Math.min(...childStarts):Infinity;if(end>latestDependencyStart){issues.push({type:"dependency-conflict",taskId:id,latestAllowedEnd:latestDependencyStart});}
 const row={...task,start,end,assignments:placed.assignments,conflict:false};scheduled.set(id,row);for(const a of placed.assignments)reservations.push({resourceId:a.resourceId,start,end,slots:a.slots,temperatureF:a.temperatureF,taskId:id});}
 const timeline=[...scheduled.values()].sort((a,b)=>a.start-b.start).map(t=>({...t,startOffsetMinutes:t.start-anchor,endOffsetMinutes:t.end-anchor,startAt:state.event?.dinnerAt?new Date(t.start*MINUTE).toISOString():null,endAt:state.event?.dinnerAt?new Date(t.end*MINUTE).toISOString():null}));
 return {anchorAt:state.event?.dinnerAt||null,tasks:timeline,issues,resources};}
