import {aggregateIngredients} from "./ingredients.js";import {deriveEquipmentPlan} from "./equipment.js";import {dishRequirementMode} from "./menu.js";import {recipeForDish,requiredServingsForDish} from "./recipes.js";import {displayQuantity,normalizeUnit,toCanonical} from "./units.js";
function allocationRecord(container,key){const value=container?.[key];if(value==null)return null;if(typeof value==="number")return {quantity:value,unit:"each"};return value;}
function compatibleAllocation(record,dimension){if(!record)return {canonicalQuantity:0,compatible:true};const unit=normalizeUnit(record.unit||"each");if(unit.dimension!==dimension)return {canonicalQuantity:0,compatible:false,record};return {canonicalQuantity:toCanonical(record.quantity??record.purchasedQuantity??0,unit.id).quantity,compatible:true,record};}
export function deriveShoppingList(state){const rows=[];for(const demand of aggregateIngredients(state)){const pantry=compatibleAllocation(allocationRecord(state.pantry,demand.key),demand.dimension);const ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,demand.key),demand.dimension);const required=demand.canonicalQuantity,have=pantry.canonicalQuantity,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-have-purchased),surplus=Math.max(0,have+purchased-required);rows.push({...demand,kind:"ingredient",requiredCanonical:required,haveCanonical:have,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,demand.dimension),alreadyHave:displayQuantity(have,demand.dimension),purchased:displayQuantity(purchased,demand.dimension),stillNeed:displayQuantity(remaining,demand.dimension),surplus:displayQuantity(surplus,demand.dimension),allocationIssues:[!pantry.compatible&&"pantry-unit-incompatible",!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean),actualCost:Number(ledger.record?.actualCost)||0});}
 for(const [dishId,dish] of Object.entries(state.dishes||{})){if(!dish?.on||dishRequirementMode(dishId,state)!=="prepared-food")continue;const recipe=recipeForDish(state,dishId);const servings=requiredServingsForDish(state,dishId);const key=`prepared:${dishId}`,dimension="serving";const ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension);const required=servings,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-purchased),surplus=Math.max(0,purchased-required);rows.push({key,name:recipe?.title||dish.title||dishId,kind:"prepared-food",dimension,canonicalQuantity:required,requiredCanonical:required,haveCanonical:0,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,quantity:required,unit:"serving",required:displayQuantity(required,dimension),alreadyHave:displayQuantity(0,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources:[{dishId,recipeId:recipe?.id||dishId,recipeTitle:recipe?.title||dish.title||dishId,quantity:servings,unit:"serving",canonicalQuantity:servings}],allocationIssues:[!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean),actualCost:Number(ledger.record?.actualCost)||0});}
 for(const need of deriveEquipmentPlan(state)){if(!need.purchaseable)continue;const key=`equipment:${need.key}`,dimension="count";const ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension);const required=need.missing,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-purchased),surplus=Math.max(0,purchased-required);if(required>0||purchased>0)rows.push({key,name:need.name,kind:"hosting-supply",dimension,quantity:required,unit:"each",requiredCanonical:required,haveCanonical:need.owned,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,dimension),alreadyHave:displayQuantity(need.owned,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources:need.sources,actualCost:Number(ledger.record?.actualCost)||0});}
 for(const item of state.manualShoppingItems||[])rows.push({...item,key:item.key||`manual:${item.id||item.name}`,kind:"manual",manual:true});return rows;}
export function setPantryQuantity(state,key,quantity,unit){return {...state,pantry:{...(state.pantry||{}),[key]:{quantity:Math.max(0,Number(quantity)||0),unit:String(unit||"each")}}};}
export function recordPurchase(state,key,quantity,unit,actualCost){const previous=state.shoppingLedger?.[key]||{};return {...state,shoppingLedger:{...(state.shoppingLedger||{}),[key]:{...previous,quantity:Math.max(0,Number(quantity)||0),unit:String(unit||previous.unit||"each"),actualCost:actualCost==null?previous.actualCost:Math.max(0,Number(actualCost)||0)}}};}
