import {aggregateIngredients} from "./ingredients.js";
import {deriveEquipmentPlan} from "./equipment.js";
import {tableSupplyRequirements} from "./table.js";
import {deriveExperiencePlan} from "./experience.js";
import {deriveTurkeyPlan} from "./turkey.js";
import {dishRequirementMode} from "./menu.js";
import {recipeForDish,requiredServingsForDish} from "./recipes.js";
import {displayQuantity,normalizeUnit,toCanonical} from "./units.js";
import {packageCount} from "./quantities.js";
function allocationRecord(container,key){const value=container?.[key];if(value==null)return null;if(typeof value==="number")return {quantity:value,unit:"each"};return value;}
function compatibleAllocation(record,dimension){if(!record)return {canonicalQuantity:0,compatible:true};const unit=normalizeUnit(record.unit||"each");if(unit.dimension!==dimension)return {canonicalQuantity:0,compatible:false,record};return {canonicalQuantity:toCanonical(record.quantity??record.purchasedQuantity??0,unit.id).quantity,compatible:true,record};}
function inventoryQty(state,key){const v=state.inventory?.[key];if(v==null)return 0;if(typeof v==="number")return Math.max(0,v);return Math.max(0,Number(v.quantity??v.owned??0)||0)+Math.max(0,Number(v.confirmedBorrowed??v.securedBorrowed??0)||0);}
function costFields(record){const actual=Math.max(0,Number(record?.actualCost)||0),committed=Math.max(actual,Math.max(0,Number(record?.committedCost)||0));return {committedCost:committed,actualCost:actual};}
function purchaseRecommendation(row){const remaining=Math.max(0,row.remainingCanonical||0);if(remaining<=0)return {quantity:0,unit:row.packageUnit||row.stillNeed?.unit||row.unit||"each",packages:0,packageQuantity:row.packageQuantity||null,packageUnit:row.packageUnit||null,estimatedPackagePrice:row.estimatedPackagePrice??null};const packageCanonical=Math.max(0,Number(row.packageCanonicalQuantity)||0);if(packageCanonical>0&&row.packageUnit&&row.packageQuantity){const packages=packageCount(remaining,packageCanonical);return {quantity:packages*Number(row.packageQuantity),unit:String(row.packageUnit),packages,packageQuantity:Number(row.packageQuantity),packageUnit:String(row.packageUnit),estimatedPackagePrice:Number.isFinite(Number(row.estimatedPackagePrice))?Number(row.estimatedPackagePrice):null,priceSource:row.priceSource||null,priceUpdatedAt:row.priceUpdatedAt||null};}const unit=row.dimension==="count"?"each":row.dimension?.startsWith("custom:")?row.dimension.slice(7):null;if(!unit)return null;const size=1;return {quantity:packageCount(remaining,size)*size,unit,packages:packageCount(remaining,size),packageQuantity:size,packageUnit:unit,estimatedPackagePrice:Number.isFinite(Number(row.estimatedPackagePrice))?Number(row.estimatedPackagePrice):null};}
function supplyRow(state,{key,name,required,kind,sources=[],estimatedUnitCost=0,owned=0,...meta}){const dimension="count",ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension),purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-owned-purchased),surplus=Math.max(0,owned+purchased-required);return {key,name,kind,dimension,quantity:required,unit:"each",requiredCanonical:required,haveCanonical:owned,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,dimension),alreadyHave:displayQuantity(owned,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources,estimatedUnitCost,...costFields(ledger.record),...meta};}
function manualRow(state,item,index){const key=item.key||`manual:${item.id||item.name||index+1}`,unit=normalizeUnit(item.unit||"each"),requiredCanonical=toCanonical(Math.max(0,Number(item.quantity)||0),unit.id).quantity,pantry=compatibleAllocation(allocationRecord(state.pantry,key),unit.dimension),ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),unit.dimension),remaining=Math.max(0,requiredCanonical-pantry.canonicalQuantity-ledger.canonicalQuantity),surplus=Math.max(0,pantry.canonicalQuantity+ledger.canonicalQuantity-requiredCanonical);return {...item,key,name:item.name||"Manual item",kind:"manual",manual:true,dimension:unit.dimension,quantity:Number(item.quantity)||0,unit:unit.id,requiredCanonical,haveCanonical:pantry.canonicalQuantity,purchasedCanonical:ledger.canonicalQuantity,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(requiredCanonical,unit.dimension,unit.id),alreadyHave:displayQuantity(pantry.canonicalQuantity,unit.dimension,unit.id),purchased:displayQuantity(ledger.canonicalQuantity,unit.dimension,unit.id),stillNeed:displayQuantity(remaining,unit.dimension,unit.id),surplus:displayQuantity(surplus,unit.dimension,unit.id),...costFields(ledger.record),allocationIssues:[!pantry.compatible&&"pantry-unit-incompatible",!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean)};}
export function deriveShoppingList(state){
 const rows=[];
 for(const demand of aggregateIngredients(state)){const pantry=compatibleAllocation(allocationRecord(state.pantry,demand.key),demand.dimension),ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,demand.key),demand.dimension),required=demand.canonicalQuantity,have=pantry.canonicalQuantity,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-have-purchased),surplus=Math.max(0,have+purchased-required);const row={...demand,kind:"ingredient",requiredCanonical:required,haveCanonical:have,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,demand.dimension),alreadyHave:displayQuantity(have,demand.dimension),purchased:displayQuantity(purchased,demand.dimension),stillNeed:displayQuantity(remaining,demand.dimension),surplus:displayQuantity(surplus,demand.dimension),allocationIssues:[!pantry.compatible&&"pantry-unit-incompatible",!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean),...costFields(ledger.record)};rows.push({...row,purchaseRecommendation:purchaseRecommendation(row)});}
 const turkey=deriveTurkeyPlan(state);
 if(turkey.dishId){const key="turkey:whole-bird",dimension="mass",requiredCanonical=toCanonical(turkey.requiredWeightLb,"lb").quantity,purchasedCanonical=toCanonical(turkey.purchasedWeightLb,"lb").quantity,remainingCanonical=Math.max(0,requiredCanonical-purchasedCanonical),surplusCanonical=Math.max(0,purchasedCanonical-requiredCanonical),ledger=allocationRecord(state.shoppingLedger,key);rows.push({key,name:turkey.recipeTitle||"Whole turkey",kind:"turkey",dimension,quantity:turkey.requiredWeightLb,unit:"lb",requiredCanonical,haveCanonical:0,purchasedCanonical,remainingCanonical,surplusCanonical,required:displayQuantity(requiredCanonical,dimension,"lb"),alreadyHave:displayQuantity(0,dimension,"lb"),purchased:displayQuantity(purchasedCanonical,dimension,"lb"),stillNeed:displayQuantity(remainingCanonical,dimension,"lb"),surplus:displayQuantity(surplusCanonical,dimension,"lb"),sources:[{dishId:turkey.dishId,recipeTitle:turkey.recipeTitle,quantity:turkey.requiredWeightLb,unit:"lb"}],...costFields(ledger)});}
 for(const [dishId,dish] of Object.entries(state.dishes||{})){if(!dish?.on||dishRequirementMode(dishId,state)!=="prepared-food")continue;const recipe=recipeForDish(state,dishId),servings=requiredServingsForDish(state,dishId),key=`prepared:${dishId}`,dimension="serving",ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension),required=servings,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-purchased),surplus=Math.max(0,purchased-required);const preparedUnitCost=Number(recipe?.preparedPurchase?.estimatedUnitCost);rows.push({key,name:recipe?.title||dish.title||dishId,kind:"prepared-food",dimension,quantity:required,unit:"serving",requiredCanonical:required,haveCanonical:0,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,dimension),alreadyHave:displayQuantity(0,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources:[{dishId,recipeId:recipe?.id||dishId,recipeTitle:recipe?.title||dish.title||dishId,quantity:servings,unit:"serving",canonicalQuantity:servings}],estimatedUnitCost:Number.isFinite(preparedUnitCost)?preparedUnitCost:null,...costFields(ledger.record)});}
 for(const need of deriveEquipmentPlan(state)){const key=`equipment:${need.key}`;if(!need.purchaseable||(!(need.required>need.owned)&&!state.shoppingLedger?.[key]))continue;rows.push(supplyRow(state,{key,name:need.name,required:need.required,owned:need.owned,kind:"hosting-supply",sources:need.sources}));}
 for(const need of tableSupplyRequirements(state)){rows.push(supplyRow(state,{key:`table:${need.key}`,name:need.name,required:need.required,owned:need.owned,kind:"table-supply",sources:[{source:"table"}],requirement:need.requirement}));}
 for(const item of deriveExperiencePlan(state).supplies){rows.push(supplyRow(state,{key:`activity:${item.key}`,name:item.name,required:item.quantity,owned:inventoryQty(state,item.key),kind:"activity-supply",sources:item.sources,estimatedUnitCost:item.estimatedUnitCost}));}
 for(const [index,item] of (state.manualShoppingItems||[]).entries())rows.push(manualRow(state,item,index));
 return rows;
}
export function setPantryQuantity(state,key,quantity,unit){return {...state,pantry:{...(state.pantry||{}),[key]:{quantity:Math.max(0,Number(quantity)||0),unit:String(unit||"each")}}};}
export function setOwnedQuantity(state,key,quantity,unit){const prefix=String(key).split(":")[0];if(!["table","equipment","activity"].includes(prefix))return setPantryQuantity(state,key,quantity,unit);const inventoryKey=String(key).slice(prefix.length+1);if(prefix==="table"&&inventoryKey.startsWith("linen:"))throw new Error("Linen ownership requires dimensions");return {...state,inventory:{...(state.inventory||{}),[inventoryKey]:{quantity:Math.max(0,Number(quantity)||0),unit:String(unit||"each")}}};}
export function recordPurchase(state,key,quantity,unit,actualCost,committedCost){const previous=state.shoppingLedger?.[key]||{},actual=actualCost==null?Math.max(0,Number(previous.actualCost)||0):Math.max(0,Number(actualCost)||0),committedInput=committedCost==null?Math.max(0,Number(previous.committedCost)||0):Math.max(0,Number(committedCost)||0),committed=Math.max(actual,committedInput);return {...state,shoppingLedger:{...(state.shoppingLedger||{}),[key]:{...previous,quantity:Math.max(0,Number(quantity)||0),unit:String(unit||previous.unit||"each"),committedCost:committed,actualCost:actual}}};}
