import {aggregateIngredients} from "./ingredients.js";
import {deriveEquipmentPlan} from "./equipment.js";
import {tableSupplyRequirements} from "./table.js";
import {deriveExperiencePlan} from "./experience.js";
import {dishRequirementMode} from "./menu.js";
import {recipeForDish,requiredServingsForDish} from "./recipes.js";
import {displayQuantity,normalizeUnit,toCanonical} from "./units.js";
function allocationRecord(container,key){const value=container?.[key];if(value==null)return null;if(typeof value==="number")return {quantity:value,unit:"each"};return value;}
function compatibleAllocation(record,dimension){if(!record)return {canonicalQuantity:0,compatible:true};const unit=normalizeUnit(record.unit||"each");if(unit.dimension!==dimension)return {canonicalQuantity:0,compatible:false,record};return {canonicalQuantity:toCanonical(record.quantity??record.purchasedQuantity??0,unit.id).quantity,compatible:true,record};}
function inventoryQty(state,key){const v=state.inventory?.[key];if(v==null)return 0;if(typeof v==="number")return Math.max(0,v);return Math.max(0,Number(v.quantity??v.owned??0)||0)+Math.max(0,Number(v.confirmedBorrowed??v.securedBorrowed??0)||0);}
function supplyRow(state,{key,name,required,kind,sources=[],estimatedUnitCost=0,owned=0}){const dimension="count",ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension),purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-owned-purchased),surplus=Math.max(0,owned+purchased-required);return {key,name,kind,dimension,quantity:required,unit:"each",requiredCanonical:required,haveCanonical:owned,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,dimension),alreadyHave:displayQuantity(owned,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources,estimatedUnitCost,actualCost:Number(ledger.record?.actualCost)||0};}
function manualRow(state,item,index){const key=item.key||`manual:${item.id||item.name||index+1}`,unit=normalizeUnit(item.unit||"each"),requiredCanonical=toCanonical(Math.max(0,Number(item.quantity)||0),unit.id).quantity,pantry=compatibleAllocation(allocationRecord(state.pantry,key),unit.dimension),ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),unit.dimension),remaining=Math.max(0,requiredCanonical-pantry.canonicalQuantity-ledger.canonicalQuantity),surplus=Math.max(0,pantry.canonicalQuantity+ledger.canonicalQuantity-requiredCanonical);return {...item,key,name:item.name||"Manual item",kind:"manual",manual:true,dimension:unit.dimension,quantity:Number(item.quantity)||0,unit:unit.id,requiredCanonical,haveCanonical:pantry.canonicalQuantity,purchasedCanonical:ledger.canonicalQuantity,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(requiredCanonical,unit.dimension,unit.id),alreadyHave:displayQuantity(pantry.canonicalQuantity,unit.dimension,unit.id),purchased:displayQuantity(ledger.canonicalQuantity,unit.dimension,unit.id),stillNeed:displayQuantity(remaining,unit.dimension,unit.id),surplus:displayQuantity(surplus,unit.dimension,unit.id),actualCost:Number(ledger.record?.actualCost)||0,allocationIssues:[!pantry.compatible&&"pantry-unit-incompatible",!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean)};}
export function deriveShoppingList(state){
 const rows=[];
 for(const demand of aggregateIngredients(state)){const pantry=compatibleAllocation(allocationRecord(state.pantry,demand.key),demand.dimension),ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,demand.key),demand.dimension),required=demand.canonicalQuantity,have=pantry.canonicalQuantity,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-have-purchased),surplus=Math.max(0,have+purchased-required);rows.push({...demand,kind:"ingredient",requiredCanonical:required,haveCanonical:have,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,demand.dimension),alreadyHave:displayQuantity(have,demand.dimension),purchased:displayQuantity(purchased,demand.dimension),stillNeed:displayQuantity(remaining,demand.dimension),surplus:displayQuantity(surplus,demand.dimension),allocationIssues:[!pantry.compatible&&"pantry-unit-incompatible",!ledger.compatible&&"purchase-unit-incompatible"].filter(Boolean),actualCost:Number(ledger.record?.actualCost)||0});}
 for(const [dishId,dish] of Object.entries(state.dishes||{})){if(!dish?.on||dishRequirementMode(dishId,state)!=="prepared-food")continue;const recipe=recipeForDish(state,dishId),servings=requiredServingsForDish(state,dishId),key=`prepared:${dishId}`,dimension="serving",ledger=compatibleAllocation(allocationRecord(state.shoppingLedger,key),dimension),required=servings,purchased=ledger.canonicalQuantity,remaining=Math.max(0,required-purchased),surplus=Math.max(0,purchased-required);rows.push({key,name:recipe?.title||dish.title||dishId,kind:"prepared-food",dimension,quantity:required,unit:"serving",requiredCanonical:required,haveCanonical:0,purchasedCanonical:purchased,remainingCanonical:remaining,surplusCanonical:surplus,required:displayQuantity(required,dimension),alreadyHave:displayQuantity(0,dimension),purchased:displayQuantity(purchased,dimension),stillNeed:displayQuantity(remaining,dimension),surplus:displayQuantity(surplus,dimension),sources:[{dishId,recipeId:recipe?.id||dishId,recipeTitle:recipe?.title||dish.title||dishId,quantity:servings,unit:"serving",canonicalQuantity:servings}],actualCost:Number(ledger.record?.actualCost)||0});}
 for(const need of deriveEquipmentPlan(state)){const key=`equipment:${need.key}`;if(!need.purchaseable||(!need.missing&&!state.shoppingLedger?.[key]))continue;rows.push(supplyRow(state,{key,name:need.name,required:need.missing,kind:"hosting-supply",sources:need.sources}));}
 for(const need of tableSupplyRequirements(state)){rows.push(supplyRow(state,{key:`table:${need.key}`,name:need.name,required:need.missing,kind:"table-supply",sources:[{source:"table"}]}));}
 for(const item of deriveExperiencePlan(state).supplies){rows.push(supplyRow(state,{key:`activity:${item.key}`,name:item.name,required:item.quantity,owned:inventoryQty(state,item.key),kind:"activity-supply",sources:item.sources,estimatedUnitCost:item.estimatedUnitCost}));}
 for(const [index,item] of (state.manualShoppingItems||[]).entries())rows.push(manualRow(state,item,index));
 return rows;
}
export function setPantryQuantity(state,key,quantity,unit){return {...state,pantry:{...(state.pantry||{}),[key]:{quantity:Math.max(0,Number(quantity)||0),unit:String(unit||"each")}}};}
export function recordPurchase(state,key,quantity,unit,actualCost){const previous=state.shoppingLedger?.[key]||{};return {...state,shoppingLedger:{...(state.shoppingLedger||{}),[key]:{...previous,quantity:Math.max(0,Number(quantity)||0),unit:String(unit||previous.unit||"each"),actualCost:actualCost==null?previous.actualCost:Math.max(0,Number(actualCost)||0)}}};}
