import {planningContext} from "./guests.js";
function qty(record){if(record==null)return 0;if(typeof record==="number")return Math.max(0,record);return Math.max(0,Number(record.quantity??record.owned??0)||0)+Math.max(0,Number(record.confirmedBorrowed??record.securedBorrowed??0)||0);}
function highChairs(state){const mode=state.planning?.mode==="confirmed"?"confirmed":"expected";let n=0;for(const g of state.guests||[]){if(mode==="confirmed"&&g.rsvp!=="yes")continue;if(mode!=="confirmed"&&g.rsvp==="no")continue;n+=Math.max(0,Number(g.highChairs)||0);}return n;}
export function normalizeTable(table={},index=0){const shape=table.shape==="round"?"round":"rectangle";return {...table,id:String(table.id||`table-${index+1}`),shape,use:String(table.use||"dining"),seatCapacity:Math.max(0,Math.floor(Number(table.seatCapacity)||0)),lengthIn:Math.max(0,Number(table.lengthIn)||0),widthIn:Math.max(0,Number(table.widthIn)||0),diameterIn:Math.max(0,Number(table.diameterIn)||0),linenDropIn:Math.max(0,Number(table.linenDropIn??12)||0)};}
export function linenRequirement(table){const t=normalizeTable(table);if(t.shape==="round")return {shape:"round",diameterIn:t.diameterIn? t.diameterIn+2*t.linenDropIn:0,dropIn:t.linenDropIn};return {shape:"rectangle",lengthIn:t.lengthIn? t.lengthIn+2*t.linenDropIn:0,widthIn:t.widthIn? t.widthIn+2*t.linenDropIn:0,dropIn:t.linenDropIn};}
function linenInventory(state){return Array.isArray(state.inventory?.linens)?state.inventory.linens:[];}
function linenFits(req,item){if((item.quantity??1)<=0)return false;if(req.shape==="round")return item.shape==="round"&&Number(item.diameterIn)>=req.diameterIn;return item.shape!=="round"&&Number(item.lengthIn)>=req.lengthIn&&Number(item.widthIn)>=req.widthIn;}
function bestLinen(state,req){const fits=linenInventory(state).filter(x=>linenFits(req,x));fits.sort((a,b)=>req.shape==="round"?(a.diameterIn-b.diameterIn):((a.lengthIn*a.widthIn)-(b.lengthIn*b.widthIn)));return fits[0]||null;}
export function deriveTablePlan(state){
 const plan=planningContext(state),tables=(state.tables||[]).map(normalizeTable),dining=tables.filter(t=>t.use==="dining"),seatCapacity=dining.reduce((n,t)=>n+t.seatCapacity,0),requiredSeats=plan.planningHeadcount,highChairNeed=highChairs(state),regularSeatNeed=Math.max(0,requiredSeats-highChairNeed);
 const chairHave=qty(state.inventory?.chairs),highChairHave=qty(state.inventory?.["high-chairs"]);const spare=Math.max(0,Number(state.planning?.placeSettingSparePercent)||0);const settings=Math.ceil(requiredSeats*(1+spare/100));
 const settingTypes=["dinner-plates","dessert-plates","forks","knives","glasses","napkins"];const placeSettings=settingTypes.map(key=>{const owned=qty(state.inventory?.[key]);return {key,name:key.replace(/-/g," "),required:settings,owned,missing:Math.max(0,settings-owned)};});
 const linens=dining.map(table=>{const requirement=linenRequirement(table),matched=bestLinen(state,requirement);return {tableId:table.id,requirement,matched,missing:matched?0:1};});
 return {tables,diningTables:dining,requiredSeats,seatCapacity,seatShortage:Math.max(0,requiredSeats-seatCapacity),regularSeatNeed,highChairNeed,chairHave,highChairHave,chairShortage:Math.max(0,regularSeatNeed-chairHave),highChairShortage:Math.max(0,highChairNeed-highChairHave),placeSettingCount:settings,placeSettings,linens};
}
export function tableSupplyRequirements(state){const p=deriveTablePlan(state),rows=[];if(p.chairShortage)rows.push({key:"chairs",name:"Chairs",required:p.chairShortage,owned:p.chairHave,missing:p.chairShortage});if(p.highChairShortage)rows.push({key:"high-chairs",name:"High chairs",required:p.highChairShortage,owned:p.highChairHave,missing:p.highChairShortage});for(const x of p.placeSettings)if(x.missing)rows.push({...x});for(const l of p.linens)if(l.missing)rows.push({key:`linen:${l.tableId}`,name:`Linen for ${l.tableId}`,required:1,owned:0,missing:1,requirement:l.requirement});return rows;}
