import {planningContext} from "./guests.js";
function qty(record){if(record==null)return 0;if(typeof record==="number")return Math.max(0,record);return Math.max(0,Number(record.quantity??record.owned??0)||0)+Math.max(0,Number(record.confirmedBorrowed??record.securedBorrowed??0)||0);}
const purchased=(state,key)=>Math.max(0,Number(state.shoppingLedger?.[`table:${key}`]?.quantity)||0);
function highChairs(state){const mode=state.planning?.mode==="confirmed"?"confirmed":"expected";let n=0;for(const g of state.guests||[]){if(mode==="confirmed"&&g.rsvp!=="yes")continue;if(mode!=="confirmed"&&g.rsvp==="no")continue;n+=Math.max(0,Number(g.highChairs)||0);}return n;}
export function normalizeTable(table={},index=0){const shape=table.shape==="round"?"round":"rectangle";return {...table,id:String(table.id||`table-${index+1}`),shape,use:String(table.use||"dining"),seatCapacity:Math.max(0,Math.floor(Number(table.seatCapacity)||0)),lengthIn:Math.max(0,Number(table.lengthIn)||0),widthIn:Math.max(0,Number(table.widthIn)||0),diameterIn:Math.max(0,Number(table.diameterIn)||0),linenDropIn:Math.max(0,Number(table.linenDropIn??12)||0)};}
export function linenRequirement(table){const t=normalizeTable(table);if(t.shape==="round")return {shape:"round",diameterIn:t.diameterIn?t.diameterIn+2*t.linenDropIn:0,dropIn:t.linenDropIn};return {shape:"rectangle",lengthIn:t.lengthIn?t.lengthIn+2*t.linenDropIn:0,widthIn:t.widthIn?t.widthIn+2*t.linenDropIn:0,dropIn:t.linenDropIn};}
function linenInventory(state){return (Array.isArray(state.inventory?.linens)?state.inventory.linens:[]).map((item,index)=>({...item,id:item.id||`linen-${index+1}`,remaining:Math.max(0,Math.floor(Number(item.quantity??1)||0))}));}
function linenOrientation(req,item){if(req.shape==="round")return item.shape==="round"&&Number(item.diameterIn)>=req.diameterIn?"normal":null;if(item.shape==="round")return null;const l=Number(item.lengthIn)||0,w=Number(item.widthIn)||0;if(l>=req.lengthIn&&w>=req.widthIn)return "normal";if(w>=req.lengthIn&&l>=req.widthIn)return "rotated";return null;}
function actualDrop(table,item,orientation){if(!item)return null;if(table.shape==="round")return Math.max(0,(Number(item.diameterIn)-table.diameterIn)/2);const l=orientation==="rotated"?Number(item.widthIn):Number(item.lengthIn),w=orientation==="rotated"?Number(item.lengthIn):Number(item.widthIn);return Math.max(0,Math.min((l-table.lengthIn)/2,(w-table.widthIn)/2));}
function allocateLinens(state,dining){const inventory=linenInventory(state),rows=[];for(const table of dining){const requirement=linenRequirement(table);const candidates=inventory.filter(item=>item.remaining>0&&linenOrientation(requirement,item)).sort((a,b)=>requirement.shape==="round"?(Number(a.diameterIn)-Number(b.diameterIn)):((Number(a.lengthIn)*Number(a.widthIn))-(Number(b.lengthIn)*Number(b.widthIn))));const matched=candidates[0]||null,orientation=matched?linenOrientation(requirement,matched):null;if(matched)matched.remaining-=1;const purchasedCount=matched?0:purchased(state,`linen:${table.id}`),covered=Boolean(matched)||purchasedCount>=1;rows.push({tableId:table.id,requirement,matched:matched?{...matched,remaining:undefined}:null,orientation,actualDropIn:matched?actualDrop(table,matched,orientation):null,purchased:purchasedCount,missing:covered?0:1});}return rows;}
export function deriveTablePlan(state){
 const plan=planningContext(state),tables=(state.tables||[]).map(normalizeTable),dining=tables.filter(t=>t.use==="dining"),seatCapacity=dining.reduce((n,t)=>n+t.seatCapacity,0),requiredSeats=plan.planningHeadcount,highChairNeed=highChairs(state),regularSeatNeed=Math.max(0,requiredSeats-highChairNeed);
 const chairHave=qty(state.inventory?.chairs),chairPurchased=purchased(state,"chairs"),highChairHave=qty(state.inventory?.["high-chairs"]),highChairPurchased=purchased(state,"high-chairs"),spare=Math.max(0,Number(state.planning?.placeSettingSparePercent)||0),settings=Math.ceil(requiredSeats*(1+spare/100));
 const settingTypes=["dinner-plates","dessert-plates","forks","knives","glasses","napkins"];const placeSettings=settingTypes.map(key=>{const owned=qty(state.inventory?.[key]),bought=purchased(state,key);return {key,name:key.replace(/-/g," "),required:settings,owned,purchased:bought,missing:Math.max(0,settings-owned-bought)};});
 const linens=allocateLinens(state,dining);
 return {tables,diningTables:dining,requiredSeats,seatCapacity,seatShortage:Math.max(0,requiredSeats-seatCapacity),regularSeatNeed,highChairNeed,chairHave,chairPurchased,highChairHave,highChairPurchased,chairShortage:Math.max(0,regularSeatNeed-chairHave-chairPurchased),highChairShortage:Math.max(0,highChairNeed-highChairHave-highChairPurchased),placeSettingCount:settings,placeSettings,linens};
}
export function tableSupplyRequirements(state){const p=deriveTablePlan(state),rows=[];if(p.regularSeatNeed>p.chairHave||state.shoppingLedger?.["table:chairs"])rows.push({key:"chairs",name:"Chairs",required:p.regularSeatNeed,owned:p.chairHave,missing:p.chairShortage});if(p.highChairNeed>p.highChairHave||state.shoppingLedger?.["table:high-chairs"])rows.push({key:"high-chairs",name:"High chairs",required:p.highChairNeed,owned:p.highChairHave,missing:p.highChairShortage});for(const x of p.placeSettings)if(x.required>x.owned||state.shoppingLedger?.[`table:${x.key}`])rows.push({...x});for(const l of p.linens)if(!l.matched||state.shoppingLedger?.[`table:linen:${l.tableId}`])rows.push({key:`linen:${l.tableId}`,name:`Linen for ${l.tableId}`,required:1,owned:l.matched?1:0,missing:l.missing,requirement:l.requirement});return rows;}
