import {build} from 'esbuild';
import {mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
await mkdir('.qa',{recursive:true});
for(const [source,name] of [['src/App.tsx','app'],['src/domain.ts','domain'],['src/printables.ts','printables'],['src/cloud.ts','cloud']]) await build({entryPoints:[source],bundle:true,platform:'node',format:'cjs',packages:'external',outfile:`.qa/${name}.cjs`,jsx:'automatic'});
await build({entryPoints:['supabase/functions/shopify-purchase/core.ts'],bundle:true,platform:'node',format:'cjs',outfile:'.qa/purchase.cjs'});
await build({entryPoints:['src/CloudApp.tsx'],bundle:true,platform:'node',format:'cjs',packages:'external',outfile:'.qa/cloud-app.cjs',jsx:'automatic',plugins:[{name:'shared-cloud-client',setup(b){b.onResolve({filter:/^\.\/cloud$/},()=>({path:'./cloud.cjs',external:true}));}}]});
execFileSync(process.execPath,['tests/domain.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/printables.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/ui.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/cloud.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/purchase.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/styles.cjs'],{stdio:'inherit'});
execFileSync(process.execPath,['tests/home-type.cjs'],{stdio:'inherit'});
