export type Activity = {
  name:string; audience:'Everyone'|'Adults + teens'|'Kids'; duration:string;
  when:string; offset:number; description:string; instructions:string[];
  prompts:string[]; supplies:{name:string;unit:string;quantity:(people:number)=>number;reusable?:boolean}[];
};
const sheets={name:'Activity printing paper',unit:'sheets',quantity:(n:number)=>n};
const pens={name:'Activity pencils',unit:'each',quantity:(n:number)=>n,reusable:true};
export const activities:Activity[]=[
 {name:'Conversation cards',audience:'Everyone',duration:'10–15 min',when:'During dinner',offset:20,description:'Questions worth passing around the table.',instructions:['Print one question sheet for every four guests; cut the prompts into strips.','Put a few prompts at each table. Take turns choosing one; anyone can pass.','Keep answers to about a minute so everyone gets a turn.'],prompts:['What small luxury makes an ordinary day better?','Which meal would you happily eat again tomorrow?','What is one thing you changed your mind about this year?','Where would you take this group for one perfect weekend?','What is a skill you would like someone here to teach you?','What is the best advice you actually followed?','What song takes you straight back to a good night?','What deserves a little more celebration?'],supplies:[{...sheets,quantity:n=>Math.ceil(n/4)}]},
 {name:'Family questions',audience:'Everyone',duration:'15–20 min',when:'With dessert',offset:75,description:'Collect the stories that never make it into the group chat.',instructions:['Pick a host to read a question aloud.','Invite someone to answer, then let another guest add their version. Passing is always welcome.','Write down a favorite story or ask permission before recording it.'],prompts:['What was your first job, and what did it teach you?','What did holidays look like when you were little?','Who in the family makes you laugh the hardest?','What is a tradition you would bring back?','What was your most memorable trip?','What is a family recipe with a story behind it?','What did you love doing at age ten?','What would you tell your younger self?'],supplies:[{...sheets,quantity:n=>Math.ceil(n/8)}]},
 {name:'Gratitude cards',audience:'Everyone',duration:'10 min',when:'Before dinner',offset:-20,description:'A short note for a person or moment that mattered.',instructions:['Give each guest a sheet and a pencil.','Choose a prompt, write a few lines and fold the note.','Guests can read it aloud, give it to someone privately or keep it.'],prompts:['A person who made this year easier…','A small moment I want to remember…','Something I am proud I kept going with…','A kindness I did not forget…','Something I look forward to sharing…','A thank-you I have been meaning to say…'],supplies:[sheets,pens]},
 {name:'Photo prompts',audience:'Everyone',duration:'10 min',when:'Before guests sit down',offset:-35,description:'A few photographs that capture the people and the night.',instructions:['Choose one person to take pictures while everyone else relaxes.','Pick three prompts; keep the photo moment short and away from hot food.','Ask before photographing or sharing anyone, especially children.'],prompts:['The host with the people who helped','Everyone in one frame','Two generations together','The table before the first plate','A candid laugh between friends','A small detail you want to remember next year'],supplies:[{...sheets,quantity:n=>Math.ceil(n/20)}]},
 {name:'After-dinner game',audience:'Adults + teens',duration:'20 min',when:'After dessert',offset:115,description:'Two truths and a wish: guess what has not happened yet.',instructions:['Divide into circles of 4–8 people.','Each person writes two true things about themselves and one thing they wish to do.','Read all three without giving away the wish. Everyone votes on which is the wish.','Reveal the answer; award one point per correct guess. Play one round per person.'],prompts:['A surprising place I have visited','A skill people do not know I have','A memorable first job','Something I once won','A future adventure','A dream class or new hobby'],supplies:[sheets,pens]},
 {name:'Kids’ table sheets',audience:'Kids',duration:'15–25 min',when:'While dinner finishes',offset:-40,description:'Drawing, spotting and a story starter for the kids’ table.',instructions:['Print one sheet per child and put pencils on the kids’ table.','An adult reads the prompts for younger children; older children can work independently.','Invite children to share their drawing when everyone has finished eating.'],prompts:['Draw your perfect dinner plate.','Design a place card for someone you love.','Find something round, striped and shiny; draw each one.','Write or draw three things that make you smile.','Finish the story: A tiny turkey knocked on the door…','Invent a dessert and give it a name.'],supplies:[sheets,pens]},
 {name:'Who knows the room?',audience:'Adults + teens',duration:'15–20 min',when:'With dessert',offset:85,description:'Match the little-known fact to the guest.',instructions:['Give each player a sheet and ask them to write one surprising, comfortable-to-share fact about themselves.','A host collects the sheets and reads the facts without names.','Everyone writes down who they think each fact belongs to.','Reveal one at a time. Score one point for each correct match; skip your own fact.'],prompts:['A place I have lived','My first concert','A hidden talent','A food I used to dislike','A childhood ambition','My most unexpected hobby'],supplies:[sheets,pens]},
 {name:'Thanksgiving charades',audience:'Everyone',duration:'20–30 min',when:'After dessert',offset:130,description:'An easy team game with no props or performance pressure.',instructions:['Print and cut the prompts. Split into teams of 3–6; large parties play in separate groups.','One player draws a prompt and acts without speaking for 60 seconds.','Their team earns one point if it guesses in time. Switch teams and actors each turn.','Play until each person has had a turn, or stop after 20 minutes.'],prompts:['Carving a turkey','Dropping a pie','Setting the table','Taking a family photo','Washing a mountain of dishes','Watching a parade','Packing leftovers','Peeling potatoes','Falling asleep after dinner','Looking for a missing chair','Whipping cream','Greeting a late guest'],supplies:[{...sheets,quantity:n=>Math.ceil(n/12)}]},
 {name:'Kids’ scavenger hunt',audience:'Kids',duration:'10–15 min',when:'Before dinner',offset:-30,description:'A supervised look-and-find game in the guest area.',instructions:['Give each child a sheet. Agree on one safe room or guest area; an adult stays with the group.','Children point to or draw each find; they do not collect or touch anything.','Keep the kitchen, stairs, candles and outdoor areas out of bounds.','Finish together and let everyone show their favorite find.'],prompts:['Something orange','A soft cushion','Something with stripes','A picture of a person','An object shaped like a circle','Something made of wood','A book','Something that makes you smile'],supplies:[sheets,pens]},
 {name:'Thanksgiving bingo',audience:'Everyone',duration:'Throughout dinner',when:'At arrival',offset:-55,description:'A small spotting game that runs quietly alongside the party.',instructions:['Print a bingo board for each guest; each new print shuffles the squares.','Cross off a square when you notice it; do not interrupt dinner to make something happen.','Three in a row wins. Share wins when the host invites them, then keep playing for a full card.'],prompts:['Someone says thank you','A guest tells a story','You hear a favorite song','Someone compliments a dish','A group photo is taken','Someone offers to help','Someone shares a memory','Dessert reaches the table','Someone asks for a recipe'],supplies:[sheets,pens]},
];
export const activityByName=(name:string)=>activities.find(a=>a.name===name);
export const activityPeople=(a:Activity,adults:number,kids:number)=>a.audience==='Kids'?kids:a.audience==='Adults + teens'?adults:adults+kids;
export function activitySheet(a:Activity){return [a.description,'',...a.instructions.map((s,i)=>`${i+1}. ${s}`),'',a.name==='Thanksgiving bingo'?'BINGO SQUARES — arrange these in a 3 × 3 grid':'PROMPTS',...a.prompts.map((p,i)=>`${i+1}. ${p}`)].join('\n');}
export function activitySupplies(selected:string[],adults:number,kids:number){
 const items=new Map<string,{name:string;unit:string;count:number;sources:string[]}>();
 for(const name of selected){const a=activityByName(name);if(!a)continue;const people=activityPeople(a,adults,kids);if(!people)continue;
 for(const supply of a.supplies){const count=supply.quantity(people),old=items.get(supply.name);items.set(supply.name,{name:supply.name,unit:supply.unit,count:old?(supply.reusable?Math.max(old.count,count):old.count+count):count,sources:[...(old?.sources||[]),name]});}}
 return [...items.values()];
}

export function printActivity(a:Activity){
 const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='0';frame.style.height='0';frame.style.border='0';document.body.append(frame);
 const doc=frame.contentDocument!;doc.open();doc.write('<!doctype html><html><head><title>Activity</title><style>@page{size:letter;margin:.65in}body{font:14px Arial,sans-serif;color:#111;line-height:1.5}header{border-bottom:1px solid #111;padding-bottom:16px}small{font-size:10px;letter-spacing:3px}h1{font-size:25px;font-weight:400;margin:14px 0}h2{font-size:16px;font-weight:400}li{margin:8px 0}.prompts{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.prompt{border:1px dashed #aaa;padding:18px;break-inside:avoid;min-height:55px}.worksheet .prompt{min-height:100px}.bingo{grid-template-columns:repeat(3,1fr);gap:0}.bingo .prompt{border:1px solid #111;min-height:80px;display:flex;align-items:center;text-align:center}.prompts:not(.bingo){break-before:page}footer{margin-top:20px;font-size:11px}</style></head><body><header><small>CROW &amp; CROWN</small><h1></h1><p></p></header><h2>How to play</h2><ol></ol><section class="prompts"></section><footer>Good nights, already figured out.</footer></body></html>');doc.close();doc.title=a.name;doc.querySelector('h1')!.textContent=a.name;doc.querySelector('header p')!.textContent=a.description;
 const instructions=a.name==='Thanksgiving bingo'?[ 'Give every player a sheet. Mark a square when you notice it during the party.', 'Three in a row wins; keep going for a full card. Share wins when the host invites them.' ]:a.instructions;
 instructions.forEach(step=>{const li=doc.createElement('li');li.textContent=step;doc.querySelector('ol')!.append(li);});
 const grid=doc.querySelector('.prompts')!;if(a.name==='Thanksgiving bingo')grid.classList.add('bingo');if(a.audience==='Kids'||a.name==='Gratitude cards'||a.name==='Who knows the room?')grid.classList.add('worksheet');
 // Each print gets a shuffled bingo board so guests can have different cards.
 const prompts=[...a.prompts];if(a.name==='Thanksgiving bingo')for(let i=prompts.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[prompts[i],prompts[j]]=[prompts[j],prompts[i]];}
 prompts.forEach(prompt=>{const card=doc.createElement('div');card.className='prompt';card.textContent=prompt;grid.append(card);});
 frame.contentWindow!.focus();frame.contentWindow!.print();setTimeout(()=>frame.remove(),60000);
}
