import type { Dish } from './App';
// Publisher batch quantities, normalized once. Summaries are original planning notes;
// the linked publisher remains the authority for the detailed cooking method.
const measured=(id:string,serves:number,source:string,sourceUrl:string,rating:string,ingredients:Dish['ingredients'],instructions:string,extra:Partial<Dish>={}):Partial<Dish>&{id:string}=>({id,serves,source,sourceUrl,rating,recipeVerified:true,cost:0,ingredients:ingredients.map(([n,q,u,c])=>[n,q/serves,u,c]),instructions,tags:[],seasoning:'Salt and pepper to taste; check pantry supplies.',...extra});
const ba='https://www.bonappetit.com/recipe/';
export const isHighlyRated=(dish:Pick<Dish,'rating'>)=>Number.parseFloat(dish.rating||'')>=4.5;
export const auditedRecipes:(Partial<Dish>&{id:string})[]=[
{id:'rolls',serves:1,sourceYield:'1 serving; 1½ prepared rolls',instructions:'Warm purchased dinner rolls according to the package directions. Serve with softened butter.',prepMinutes:3,seasoning:'Use the package temperature and heating time if different from this planning estimate.'},
measured('signature-cocktail',2,'Pook’s Pantry','https://www.pookspantry.com/apple-cider-bourbon-cocktail/','4.5 ★ · 22 votes',[
['Apple cider',1,'cup','Beverages'],['Bourbon',3,'fl oz','Beverages'],['Nutmeg',.25,'tsp','Pantry'],['Sugar',1,'tsp','Pantry'],['Brown sugar',1,'tsp','Pantry'],['Cinnamon',.25,'tsp','Pantry'],['Lemon juice',1,'tsp','Produce']],
'Moisten two glass rims with lemon juice and dip into combined sugars, cinnamon and half the nutmeg. Shake cider, bourbon and remaining nutmeg with ice, then divide between the glasses.',{name:'Apple cider bourbon cocktail',sourceYield:'2 cocktails; plan 1 per adult drinker',portion:'1 cocktail per adult drinker',minutes:11,prepMinutes:11,oven:0,temp:0,makeAhead:'Chill cider; mix the spiced rim sugar ahead.',seasoning:'Ice as needed; optional apple, cinnamon-stick and lemon garnish.',audience:'adults'}),
measured('mac',4,'Allrecipes', 'https://www.allrecipes.com/recipe/11679/homemade-mac-and-cheese/','4.5 ★ · 2,623 ratings',[
['Elbow macaroni',8,'oz','Pantry'],['Butter',6,'tbsp','Dairy'],['Flour',3,'tbsp','Pantry'],['Milk',3,'cup','Dairy'],['Cheddar cheese',2,'cup','Dairy'],['Parmesan',.5,'cup','Dairy'],['Bread crumbs',.5,'cup','Bakery']],
'Boil and drain pasta. Make a butter–flour roux; gradually stir in milk and melt cheeses. Combine with pasta, add buttered crumbs and paprika, then bake until bubbling.',{sourceYield:'4 servings; 8 inch square casserole',minutes:55,prepMinutes:25,oven:30,temp:350,batchMode:'whole',seasoning:'Salt, pepper and a pinch of paprika.',vessel:'8 inch square baker',makeAhead:'Best baked near serving; refrigerate leftovers.'}),
measured('app',6,'Fork in the Kitchen','https://www.forkinthekitchen.com/whipped-ricotta-with-herbs-and-honey/','5 ★ · 128 ratings',[
['Ricotta',1,'cup','Dairy'],['Mint',2,'tbsp','Produce'],['Parsley',1,'tsp','Produce'],['Lemon zest',.5,'tsp','Produce'],['Olive oil',1,'tbsp','Pantry'],['Honey',3,'tsp','Pantry'],['Baguette',1,'each','Bakery']],
'Beat ricotta until airy. Mix herbs, zest, oil and honey; spoon over the cheese. Toast lightly oiled baguette slices at 375°F for 5–7 minutes, turning halfway, and serve alongside.',{sourceYield:'6 appetizer servings',minutes:17,prepMinutes:10,oven:7,temp:375,seasoning:'Salt and pepper; extra olive oil for brushing bread.',makeAhead:'Prepare ricotta ahead; toast bread near service.',tags:['Vegetarian']}),
measured('ba-dry-turkey',8,'Bon Appétit',ba+'dry-rubbed-roast-turkey','4.6 ★ · 135 ratings',[
['Turkey',1,'12–14 lb bird','Meat'],['Diamond Crystal kosher salt',.5,'cup','Pantry'],['Brown sugar',1,'tbsp','Pantry'],['Butter',12,'tbsp','Dairy'],['Sherry vinegar',.25,'cup','Pantry'],['Honey',2,'tbsp','Pantry'],['Worcestershire sauce',4,'tsp','Pantry'],['Rosemary',3,'sprig','Produce'],['Garlic',3,'clove','Produce'],['Orange zest',2,'strip','Produce'],['Water',1,'cup','Kitchen']],
'Dry-brine uncovered in the refrigerator for 12–48 hours. Butter the bird. Start roasting at 450°F, then lower to 300°F and glaze regularly. Check doneness with a thermometer; rest before carving. Read the source for its temperature and carryover instructions.',{sourceYield:'8–10 servings; one 12–14 lb bird',minutes:175,prepMinutes:30,oven:115,temp:300,restMinutes:30,batchMode:'whole',ovenStages:[{label:'Initial roast',minutes:30,temp:450},{label:'Glaze and finish roasting',minutes:85,temp:300}],makeAhead:'Dry-brine 12–48 hours ahead; thaw fully first.',seasoning:'Diamond Crystal salt measured; Morton requires less. Extra water as needed. Worcestershire typically contains fish.'}),
measured('ba-simple-stuffing',8,'Bon Appétit',ba+'simple-is-best-stuffing-dressing','4.6 ★ · 495 ratings',[
['Butter',.75,'cup','Dairy'],['Bread',1,'lb','Bakery'],['Onions',2.5,'cup','Produce'],['Celery',1.5,'cup','Produce'],['Parsley',.5,'cup','Produce'],['Sage',2,'tbsp','Produce'],['Rosemary',1,'tbsp','Produce'],['Thyme',1,'tbsp','Produce'],['Kosher salt',2,'tsp','Pantry'],['Black pepper',1,'tsp','Pantry'],['Chicken broth',2.5,'cup','Pantry'],['Eggs',2,'each','Dairy']],
'Dry bread at 250°F. Sauté vegetables in butter and combine with bread, herbs and half the broth; cool. Fold in eggs whisked with remaining broth. Bake covered at 350°F, then uncover to crisp.',{sourceYield:'8–10 servings',minutes:205,prepMinutes:30,oven:85,temp:350,batchMode:'whole',ovenStages:[{label:'Dry bread',minutes:60,temp:250},{label:'Bake covered, then crisp uncovered',minutes:85,temp:350,waitBefore:30}],vessel:'9 × 13 inch baker',makeAhead:'Dry bread ahead; see source for the separate refrigerated reheat method.',seasoning:'Measured seasonings above; extra butter for the pan.'}),
measured('ba-mashed',8,'Bon Appétit',ba+'best-mashed-potatoes','4.6 ★ · 94 ratings',[
['Yukon Gold potatoes',4,'lb','Produce'],['Diamond Crystal kosher salt',4,'tsp','Pantry'],['Milk',1.5,'cup','Dairy'],['Cream',.5,'cup','Dairy'],['Garlic',1,'head','Produce'],['Rosemary',3,'sprig','Produce'],['Butter',1,'cup','Dairy']],
'Simmer whole potatoes until tender, drain and rice while hot. Warm milk and cream with garlic and rosemary; strain. Stir butter into potatoes and gradually add warm dairy.',{sourceYield:'8 servings',minutes:60,prepMinutes:60,oven:0,temp:0,tags:['Vegetarian','Gluten-Free','Nut-Free','Egg-Free'],seasoning:'Diamond Crystal salt measured; Morton requires less. Extra salt for cooking water; pepper to finish.',makeAhead:'Refrigerate up to one day; reheat gently with a little milk.'}),
measured('ba-honey-brussels',4,'Bon Appétit',ba+'roasted-brussels-sprouts-with-warm-honey-glaze','4.7 ★ · 160 ratings',[
['Brussels sprouts',1.5,'lb','Produce'],['Olive oil',.25,'cup','Pantry'],['Kosher salt',.5,'tsp','Pantry'],['Honey',.25,'cup','Pantry'],['Sherry vinegar',1/3,'cup','Pantry'],['Butter',3,'tbsp','Dairy'],['Scallions',3,'each','Produce'],['Lemon zest',1,'tsp','Produce']],
'Roast oiled sprouts cut-side-down on a hot tray at 450°F for 20–25 minutes. Reduce honey, carefully add vinegar, then whisk in butter. Toss sprouts with glaze and scallions; finish with zest.',{sourceYield:'4 servings',minutes:40,prepMinutes:15,oven:25,temp:450,tags:['Vegetarian','Gluten-Free','Nut-Free','Egg-Free'],seasoning:'Pepper and extra salt; optional red pepper flakes.',makeAhead:'Trim sprouts ahead; roast close to dinner.'}),
measured('ba-greenbeans',8,'Bon Appétit',ba+'green-beans-and-mushrooms-with-crispy-shallots','4.7 ★ · 51 ratings',[
['Green beans',1.5,'lb','Produce'],['Diamond Crystal kosher salt',1.5,'tsp','Pantry'],['Vegetable oil',1/3,'cup','Pantry'],['Shallots',3,'each','Produce'],['Mushrooms',1,'lb','Produce'],['Butter',4,'tbsp','Dairy'],['Sherry vinegar',2,'tbsp','Pantry'],['Parmesan',2,'oz','Dairy']],
'Blanch beans and cool. Fry shallots in oil, then remove. Brown mushrooms in the same pan; add butter and beans. Finish with vinegar, Parmesan and crispy shallots.',{sourceYield:'8 servings',minutes:45,prepMinutes:45,oven:0,temp:0,seasoning:'Diamond Crystal salt measured; Morton requires less. Pepper and extra salt to taste.',makeAhead:'Blanch beans one day ahead.',tags:['Gluten-Free','Nut-Free','Egg-Free']}),
measured('ba-pumpkin-pie',8,'Bon Appétit',ba+'best-pumpkin-pie','4.5 ★ · 64 ratings',[
['Pie crust',1,'9 inch unbaked crust','Frozen'],['Eggs',4,'each','Dairy'],['Sugar',1/3,'cup','Pantry'],['Cinnamon',1,'tsp','Pantry'],['Diamond Crystal kosher salt',.75,'tsp','Pantry'],['Ginger',.5,'tsp','Pantry'],['Cloves',.25,'tsp','Pantry'],['Nutmeg',.25,'tsp','Pantry'],['Pumpkin purée',2,'cup','Pantry'],['Sweetened condensed milk',2/3,'cup','Dairy'],['Cream',1/3,'cup','Dairy'],['Maple syrup',2,'tbsp','Pantry'],['Vanilla extract',2,'tsp','Pantry']],
'Chill shaped crust. Blind-bake at 425°F; remove weights, egg-wash inside and bake at 350°F. Cool. Whisk filling using two whole eggs plus one yolk; bake at 325°F until edges set, then cool completely.',{sourceYield:'One 9 inch pie; 8 planned slices',minutes:395,prepMinutes:60,oven:125,temp:325,restMinutes:180,batchMode:'whole',ovenStages:[{label:'Blind-bake weighted crust',minutes:35,temp:425},{label:'Set egg-washed crust',minutes:15,temp:350},{label:'Bake pumpkin filling',minutes:75,temp:325,waitBefore:30}],vessel:'9 inch pie plate',makeAhead:'Bake and refrigerate one day ahead.',seasoning:'4 eggs purchased: 1 for crust, 2 whole plus 1 yolk for filling. Flour for rolling; optional whipped cream.'}),
measured('ba-parker-rolls',7,'Sally’s Baking','https://sallysbakingaddiction.com/soft-dinner-rolls/','4.8 ★ · 1,079 reviews',[
['Milk',1,'cup','Dairy'],['Instant yeast',2.25,'tsp','Pantry'],['Sugar',2,'tbsp','Pantry'],['Eggs',1,'each','Dairy'],['Butter',.25,'cup','Dairy'],['Salt',1,'tsp','Pantry'],['Flour',3,'cup','Pantry']],
'Activate yeast in 110°F milk with half the sugar. Mix remaining dough ingredients and knead five minutes. Rise until doubled, 1–2 hours. Shape 14 rolls; rise about one hour. Bake at 350°F for 20–25 minutes until golden.',{name:'Soft homemade dinner rolls',sourceYield:'14–16 rolls; 7 planned servings of 2 rolls',portion:'2 homemade rolls per guest',minutes:230,prepMinutes:205,oven:25,temp:350,batchMode:'whole',vessel:'9 × 13 inch baker',makeAhead:'See source for overnight shaped-roll refrigeration and the next-day rise.',seasoning:'Extra flour for kneading, oil for bowl. Optional honey-butter topping.',tags:['Vegetarian','Nut-Free']}),
measured('ba-roasted-sweet',4,'Cookie and Kate','https://cookieandkate.com/roasted-sweet-potatoes-recipe/','4.8 ★ · 18 reviews',[
['Sweet potatoes',2,'lb','Produce'],['Olive oil',2,'tbsp','Pantry'],['Sea salt',.25,'tsp','Pantry']],
'Cut potatoes into one-inch cubes, coat with oil and salt, and spread in a single layer. Roast at 425°F for 30–40 minutes, turning halfway, until tender with caramelized edges.',{sourceYield:'4 side servings',minutes:50,prepMinutes:10,oven:40,temp:425,tags:['Vegan','Vegetarian','Gluten-Free','Dairy-Free','Egg-Free','Nut-Free'],seasoning:'Optional chili powder or black pepper to taste.',makeAhead:'Cut ahead; roast near service.'}),
measured('ba-fancy-cranberry',8,'Bon Appétit',ba+'fancy-cranberry-sauce','4.7 ★ · 26 ratings',[
['Gelatin',1.5,'tbsp','Pantry'],['Water',.5,'cup','Kitchen'],['Cranberries',1.5,'lb','Produce'],['Cardamom pods',4,'each','Pantry'],['Bay leaves',3,'each','Produce'],['Cranberry juice',1,'cup','Beverages'],['Sugar',1.6875,'cup','Pantry'],['Orange zest',2,'strip','Produce']],
'Bloom gelatin. Simmer cranberries with juice, most sugar and aromatics; discard pods and bay. Dissolve gelatin into berries, pour into a greased mold and chill at least 12 hours. Unmold and garnish with reserved sugared berries and zest.',{sourceYield:'8–10 servings',minutes:750,prepMinutes:30,restMinutes:720,oven:0,temp:0,batchMode:'whole',vessel:'4 cup mold',makeAhead:'Make at least 12 hours and up to 2 days ahead.',seasoning:'Pinch of salt; oil spray for mold. Gelatin is not vegetarian.'}),
measured('allrecipes-corn',8,'Allrecipes','https://www.allrecipes.com/recipe/18906/awesome-and-easy-creamy-corn-casserole/','4.7 ★ · 4,054 ratings',[
['Whole kernel corn',1,'15 oz can','Pantry'],['Creamed corn',1,'14.75 oz can','Pantry'],['Cornbread mix',1,'8.5 oz package','Bakery'],['Sour cream',1,'cup','Dairy'],['Butter',.5,'cup','Dairy'],['Eggs',2,'each','Dairy']],
'Drain whole corn. Combine both corns with mix, sour cream, melted butter and beaten eggs. Spread in a greased pan; bake at 350°F for about 45 minutes until the center sets.',{sourceYield:'8 servings; 9 inch square casserole',minutes:55,prepMinutes:10,oven:45,temp:350,batchMode:'whole',vessel:'9 inch square baker',makeAhead:'Bake up to two days ahead; refrigerate.',seasoning:'Butter for greasing; choose a vegetarian cornbread mix.',tags:['Vegetarian']}),
measured('allrecipes-broccoli-cheese',8,'Allrecipes','https://www.allrecipes.com/recipe/13606/awesome-broccoli-cheese-casserole/','4.7 ★ · 696 ratings',[
['Cream of mushroom soup',1,'10.5 oz can','Pantry'],['Mayonnaise',1,'cup','Pantry'],['Eggs',1,'each','Dairy'],['Onions',.25,'cup','Produce'],['Frozen broccoli',30,'oz','Frozen'],['Cheddar cheese',8,'oz','Dairy']],
'Whisk soup, mayonnaise, egg and onion. Combine with broccoli and cheese in a greased pan, season and bake at 350°F for 45–60 minutes until hot and golden.',{sourceYield:'8 servings',minutes:75,prepMinutes:15,oven:60,temp:350,batchMode:'whole',vessel:'9 × 13 inch baker',makeAhead:'Bake close to service.',seasoning:'Salt, pepper and paprika; butter for greasing.',tags:['Vegetarian']}),
measured('fn-vegan-greenbean',4,'Minimalist Baker','https://minimalistbaker.com/vegan-green-bean-casserole/','4.96 ★ · 263 votes',[
['Green beans',1,'lb','Produce'],['Olive oil',2,'tbsp','Pantry'],['Shallots',1,'each','Produce'],['Garlic',2,'clove','Produce'],['Mushrooms',1,'cup','Produce'],['Flour',2,'tbsp','Pantry'],['Vegetable broth',.75,'cup','Pantry'],['Unsweetened almond milk',1,'cup','Pantry'],['Vegan crispy onions',1.5,'cup','Pantry']],
'Blanch beans and ice-cool. Sauté shallot, garlic and mushrooms; stir in flour, broth and almond milk to thicken. Fold in beans and one-third onions; top with remaining onions and bake at 400°F for 15 minutes.',{sourceYield:'4 servings',minutes:45,prepMinutes:30,oven:15,temp:400,tags:['Vegan','Vegetarian','Dairy-Free','Egg-Free'],makeAhead:'Prepare components ahead; assemble and bake near service.',seasoning:'Salt and pepper; check fried onions are vegan. Contains almonds and wheat.'}),
measured('fn-gf-cornbread',8,'Dish by Dish','https://www.dishbydish.net/gluten-free-skillet-cornbread/','5 ★ · 7 reviews',[
['Gluten-free cornmeal',1.25,'cup','Pantry'],['Gluten-free flour',.75,'cup','Pantry'],['Xanthan gum',.5,'tsp','Pantry'],['Brown sugar',.25,'cup','Pantry'],['Salt',1,'tsp','Pantry'],['Gluten-free baking powder',3,'tsp','Pantry'],['Unsweetened almond milk',4/3,'cup','Pantry'],['Eggs',2,'each','Dairy'],['Coconut oil',.5,'cup','Pantry']],
'Heat skillet at 425°F while mixing batter. Reserve a tablespoon of oil for the skillet. Lower oven to 375°F, oil the hot skillet and add batter. Bake 25–30 minutes; cool 10–15 minutes.',{sourceYield:'8 wedges',minutes:60,prepMinutes:15,oven:30,temp:375,restMinutes:15,batchMode:'whole',vessel:'8 inch cast-iron skillet',makeAhead:'Bake on the day; cool before slicing.',tags:['Vegetarian','Gluten-Free','Dairy-Free'],seasoning:'Omit added xanthan if the flour blend contains it. Contains eggs and almonds.'}),
measured('ew-stuffed-squash',4,'Budget Bytes','https://www.budgetbytes.com/wild-rice-stuffed-acorn-squash/','4.8 ★ · 20 votes',[
['Acorn squash',2,'each','Produce'],['Wild rice blend',.5,'cup','Pantry'],['Vegetable broth',1,'cup','Pantry'],['Vegan butter',2,'tbsp','Pantry'],['Onions',1,'each','Produce'],['Celery',3,'stalk','Produce'],['Apples',1,'each','Produce'],['Dried sage',.5,'tsp','Pantry'],['Dried thyme',.5,'tsp','Pantry'],['Salt',.375,'tsp','Pantry'],['Black pepper',.375,'tsp','Pantry'],['Walnuts',.25,'cup','Pantry'],['Dried cranberries',.25,'cup','Pantry'],['Parsley',1,'tbsp','Produce']],
'Simmer rice in broth for 45 minutes. Roast seasoned squash halves cut-side-down at 400°F for 20 minutes. Sauté vegetables and apple; combine with rice, nuts, cranberries and parsley. Fill squash and bake another 20 minutes.',{sourceYield:'4 servings; one squash half each',minutes:80,prepMinutes:15,oven:40,temp:400,batchMode:'whole',ingredientSteps:{'Acorn squash':1},ovenStages:[{label:'Roast squash halves',minutes:20,temp:400},{label:'Bake filled squash',minutes:20,temp:400,waitBefore:25}],tags:['Vegan','Vegetarian','Dairy-Free','Egg-Free'],vessel:'Sheet pan + skillet',makeAhead:'Cook filling ahead; chill until needed.',seasoning:'Use the publisher’s vegan-butter option; contains walnuts.'}),
measured('fn-citrus-cranberry',9,'Once Upon a Chef','https://www.onceuponachef.com/recipes/cranberry-sauce.html','4.94 ★ · 215 votes',[
['Water',.5,'cup','Kitchen'],['Oranges',2,'each','Produce'],['Sugar',.875,'cup','Pantry'],['Cranberries',12,'oz','Produce']],
'Zest one orange and juice both for half a cup of juice. Boil water, juice and sugar; add berries, zest and salt. Simmer gently 10–12 minutes until berries burst, then cool and refrigerate.',{sourceYield:'2¼ cups; 9 planned ¼-cup portions',minutes:45,prepMinutes:17,restMinutes:28,oven:0,temp:0,tags:['Vegan','Vegetarian','Gluten-Free','Dairy-Free','Egg-Free','Nut-Free'],makeAhead:'Refrigerate ahead of dinner.',seasoning:'Pinch of salt; orange yield varies—measure ½ cup juice.'}),
];
export const pecanRecipe: Dish={
 id:'guide-pecan',name:'Classic pecan pie',group:'Dessert',style:'reader-favorite',serves:8,sourceYield:'Source: 12 slices; planned as 8 larger slices per 9 inch pie',source:'Allrecipes',sourceUrl:'https://www.allrecipes.com/recipe/18433/irresistible-pecan-pie/',rating:'4.7 ★ · 720 ratings',recipeVerified:true,
 ingredients:[['Flour',1.5,'cup','Pantry'],['Salt',.5,'tsp','Pantry'],['Sugar',2,'tbsp','Pantry'],['Butter',11,'tbsp','Dairy'],['Water',.25,'cup','Kitchen'],['Eggs',3,'each','Dairy'],['Light corn syrup',.75,'cup','Pantry'],['Dark corn syrup',2,'tbsp','Pantry'],['Brown sugar',.75,'cup','Pantry'],['Pecans',2.5,'cup','Pantry']].map(([n,q,u,c])=>[String(n),Number(q)/8,String(u),String(c)]),
 instructions:'Make pastry with flour, salt, sugar, eight tablespoons cold butter and ice water; roll into the pie plate and chill. Mix eggs, syrups, brown sugar, three tablespoons melted butter and crushed pecans. Layer remaining pecans and filling inside; bake at 350°F until set and cool.',
 minutes:145,prepMinutes:25,oven:60,temp:350,restMinutes:60,batchMode:'whole',cost:0,easyCost:0,portion:'One generous slice per guest',vessel:'9 inch pie plate',easier:'Bakery pecan pie',makeAhead:'Bake before dinner; cool completely before slicing.',finish:'Cool completely and slice at dessert.',seasoning:'Extra pinch of salt for filling; extra flour for rolling. Pecans: ½ cup crushed, 1 cup quartered, 1 cup halves. Contains pecans, eggs, dairy and wheat.',tags:['Vegetarian']
};
