import type { State, Dish } from './App';
// Port of the canonical v3 architecture in Thanksgiving-/bf9dc61, adapted to the approved React interface.
export const uid = (prefix='id') => `${prefix}-${crypto.randomUUID()}`;
const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Math.max(0,Number(v)):f;
const integer=(v:unknown,f=0)=>Math.floor(num(v,f));
const object=(v:any)=>v && typeof v==='object' && !Array.isArray(v)?v:{};
const array=(v:any)=>Array.isArray(v)?v:[];
const strings=(v:any)=>array(v).filter(x=>typeof x==='string');
const text=(v:any,f='')=>typeof v==='string'?v:f;
const choice=(v:any,opts:string[],fallback:string)=>opts.includes(v)?v:fallback;
export function nextThanksgiving(now=new Date()) {let y=now.getFullYear();const date=(year:number)=>{const d=new Date(year,10,1,12);d.setDate(1+(4-d.getDay()+7)%7+21);return d;};let d=date(y);if(d<now)d=date(++y);return `${y}-11-${String(d.getDate()).padStart(2,'0')}`;}
function migrateV1toV2(raw:any) {
 const r={...raw,schemaVersion:2};r.guests=array(raw.guests).filter(g=>g&&typeof g==='object').map(g=>({...g,guestId:text(g.guestId)||uid('guest')}));
 r.seating={};for(const g of r.guests){const byName=r.guests.filter((x:any)=>x.name===g.name);const seat=raw.seating?.[g.guestId] || (byName.length===1?raw.seating?.[g.name]:null);if(seat)r.seating[g.guestId]=/^\d+$/.test(seat)?`main-1:seat-${seat}`:seat;}
 r.menuPlan={...object(raw.menuPlan)};for(const [id,owner] of Object.entries(object(raw.menuOwners))){if(r.menuPlan[id])continue;const matches=r.guests.filter((g:any)=>`Guest: ${g.name}`===owner);r.menuPlan[id]={owner:owner==='Host'?'Host':matches.length===1?matches[0].guestId:'Other',status:'Planned',preparation:strings(raw.easy).includes(id)?'Purchased':'Homemade'};}
 return r;
}
function migrateV2toV3(raw:any){return {...raw,schemaVersion:3,shoppingOverrides:{...Object.fromEntries(Object.entries(object(raw.shoppingQtyOverrides)).map(([k,v])=>[k,{mode:'locked',value:num(v)}])),...object(raw.shoppingOverrides)}};}
// The prior Hosting Site also labeled its older menuOwners/numeric-seat shape v3.
// Convert that shape before applying the new v4 model, including saved archives.
function migrateV3toV4(raw:any){
 const guests=array(raw.guests),menuPlan={...object(raw.menuPlan)};
 for(const [dishId,legacyOwner] of Object.entries(object(raw.menuOwners))){
  if(menuPlan[dishId])continue;
  let owner='Host',status='Confirmed';
  if(legacyOwner==='Guest: Someone else'){owner='Other';status='Planned';}
  else if(typeof legacyOwner==='string'&&legacyOwner.startsWith('Guest: ')){
   const ref=legacyOwner.slice(7),matches=guests.filter((g:any)=>g?.guestId===ref||g?.name===ref);
   if(matches.length===1){owner=text(matches[0].guestId);status=choice(matches[0].status,['Not confirmed','Confirmed','Arrived'],'Not confirmed')==='Arrived'?'Arrived':matches[0].status==='Confirmed'?'Confirmed':'Planned';}
   else {owner='Other';status='Planned';}
  }
  menuPlan[dishId]={owner,status,preparation:strings(raw.easy).includes(dishId)?'Purchased':'Homemade'};
 }
 const capacity=Math.max(2,integer(raw.tableCapacity,8));const assigned=Object.entries(object(raw.seating));
 const numeric=assigned.filter(([,seat])=>typeof seat==='string'&&/^\d+$/.test(seat)).sort((a,b)=>Number(a[1])-Number(b[1]));
 const childRank=new Map(numeric.filter(([id])=>guests.some((g:any)=>g?.guestId===id&&g?.ageGroup==='Child')).map(([id],i)=>[id,i]));
 const seating=Object.fromEntries(assigned.map(([id,seat])=>{
  if(typeof seat!=='string')return[id,seat];
  const legacy=/^main-1:seat-(\d+)$/.exec(seat);const n=/^\d+$/.test(seat)?Number(seat):legacy?Number(legacy[1]):0;
  if(!n)return[id,seat];
  const kid=!!raw.kidsTable&&childRank.has(id),index=kid?childRank.get(id)!:n-1,limit=kid?6:capacity;
  return[id,`${kid?'kids':'main'}-${Math.floor(index/limit)+1}:seat-${index%limit+1}`];
 }));
 return {...raw,menuPlan,seating,schemaVersion:4};
}
export function normalizeState(input:unknown,defaults:State,catalog:Dish[]):State {
 let raw=object(input);if(num(raw.schemaVersion)>4)throw new Error('This plan was saved by a newer app version.');if(num(raw.schemaVersion)<2)raw=migrateV1toV2(raw);if(num(raw.schemaVersion)<3)raw=migrateV2toV3(raw);if(num(raw.schemaVersion)<4)raw=migrateV3toV4(raw);
 const s:any={...structuredClone(defaults)};
 for(const [k,v] of Object.entries(defaults)) {if(typeof v==='number')s[k]=num(raw[k],v);else if(typeof v==='boolean')s[k]=typeof raw[k]==='boolean'?raw[k]:v;else if(typeof v==='string')s[k]=text(raw[k],v);}
 const ids=new Set<string>();s.guests=array(raw.guests??defaults.guests).filter(g=>g&&typeof g==='object').map(g=>{let id=text(g.guestId)||uid('guest');if(ids.has(id))id=uid('guest');ids.add(id);return {guestId:id,name:text(g.name),rsvp:choice(g.rsvp,['Attending','Pending','Declined'],'Pending'),ageGroup:choice(g.ageGroup,['Adult','Child'],'Adult'),alcohol:g.ageGroup==='Child'?false:typeof g.alcohol==='boolean'?g.alcohol:null,kidBeverage:text(g.kidBeverage),diet:text(g.diet),dietaryNeeds:strings(g.dietaryNeeds),dish:text(g.dish),status:choice(g.status,['Not confirmed','Confirmed','Arrived'],'Not confirmed'),note:text(g.note)};});
 for(const [key,opts] of Object.entries({service:['Buffet','Seated dinner','Cocktail-style'],fridge:['Tight','Limited','Moderate','Generous'],appetite:['Lighter','Standard','Generous'],turkey:['Whole turkey','Turkey breast'],drink:['Wine-focused','Signature cocktail','One signature cocktail','Full bar','No-alcohol-forward','Mixed','Nonalcoholic-forward']}))s[key]=choice(s[key],opts,(defaults as any)[key]);
 s.planningMode=choice(raw.planningMode,['Estimated','Expected','Confirmed','Custom'],'Estimated');
 s.customRecipes=array(raw.customRecipes).filter(d=>d&&typeof d==='object'&&typeof d.name==='string').map(d=>({...d,id:text(d.id)||uid('dish'),group:text(d.group,'Starch'),style:'custom',minutes:num(d.minutes),oven:num(d.oven),temp:num(d.temp,350),cost:num(d.cost),easyCost:num(d.easyCost),serves:Math.max(1,num(d.serves,1)),portion:text(d.portion),vessel:text(d.vessel,'Serving dish'),easier:text(d.easier),makeAhead:text(d.makeAhead),finish:text(d.finish),instructions:text(d.instructions),batchMode:d.batchMode==='whole'||d.batchMode==='half'?d.batchMode:undefined,ingredientSteps:Object.fromEntries(Object.entries(object(d.ingredientSteps)).filter(([,v])=>Number.isFinite(Number(v))&&Number(v)>0).map(([k,v])=>[k,Number(v)])),prepMinutes:num(d.prepMinutes),restMinutes:num(d.restMinutes),sourceYield:text(d.sourceYield),seasoning:text(d.seasoning),ovenStages:array(d.ovenStages).filter(x=>x&&num(x.minutes)>0&&num(x.temp)>0).map(x=>({label:text(x.label),minutes:num(x.minutes),temp:num(x.temp),waitBefore:num(x.waitBefore),restAfter:num(x.restAfter)})),image:/^\/resources\//.test(text(d.image))?text(d.image):'',sourceUrl:/^https?:\/\//.test(text(d.sourceUrl))?text(d.sourceUrl):'',ingredients:array(d.ingredients).filter(x=>Array.isArray(x)&&typeof x[0]==='string').map(x=>[x[0],num(x[1]),text(x[2],'each'),text(x[3],'Custom')]),tags:strings(d.tags)}));
 for(const k of ['selections','easy','purchased','done','borrowed','activities','hiddenShopping'])s[k]=strings(raw[k]??defaults[k as keyof State]);s.inspiration=strings(raw.inspiration).filter(x=>/^data:image\/(png|jpeg|webp);base64,/.test(x));
 for(const k of ['seating','unitPrices','timelineOverrides'])s[k]=Object.fromEntries(Object.entries(object(raw[k])).filter(([,v])=>k==='seating'?typeof v==='string':Number.isFinite(Number(v))).map(([key,v])=>[key,k==='seating'?v:k==='timelineOverrides'?Number(v):num(v)]));
 s.menuPlan={};for(const [id,v] of Object.entries(object(raw.menuPlan))){const r=object(v);s.menuPlan[id]={owner:text(r.owner,'Host'),status:choice(r.status,['Planned','Confirmed','Arrived'],'Planned'),preparation:choice(r.preparation,['Homemade','Purchased'],'Homemade')};}
 s.shoppingOverrides={};for(const [id,v] of Object.entries(object(raw.shoppingOverrides))){const o=object(v);if(Number.isFinite(Number(o.value)))s.shoppingOverrides[id]={mode:o.mode==='locked'?'locked':'adjustment',value:o.mode==='locked'?num(o.value):Number(o.value)};}
 s.printableOverrides={};for(const [id,v] of Object.entries(object(raw.printableOverrides))){const o=object(v);s.printableOverrides[id]={...(typeof o.name==='string'?{name:o.name}:{}),...(typeof o.desc==='string'?{desc:o.desc}:{})};}
 s.drafts=object(raw.drafts);s.actualSpend=array(raw.actualSpend).filter(x=>x&&typeof x==='object').map(x=>({id:text(x.id)||uid('spend'),label:text(x.label),amount:num(x.amount)}));
 s.customShoppingItems=array(raw.customShoppingItems).filter(x=>x&&typeof x==='object').map(x=>({id:text(x.id)||uid('shopping'),name:text(x.name),quantity:num(x.quantity),unit:text(x.unit,'each'),category:text(x.category,'Custom')}));
 s.customPrepTasks=array(raw.customPrepTasks).filter(x=>x&&typeof x==='object').map(x=>({id:text(x.id)||uid('prep'),label:text(x.label),phase:choice(x.phase,['DO FIRST','1–2 DAYS BEFORE','THANKSGIVING DAY','FINAL 60 MINUTES'],'DO FIRST')}));
 s.customTimelineItems=array(raw.customTimelineItems).filter(x=>x&&typeof x==='object').map(x=>({id:text(x.id)||uid('timeline'),label:text(x.label),time:/^([01]\d|2[0-3]):[0-5]\d$/.test(x.time)?x.time:s.time,category:text(x.category,'Activity')}));
 if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.time))s.time=defaults.time;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.hostBuffer))s.hostBuffer=defaults.hostBuffer;
 if(!/^\d{4}-\d{2}-\d{2}$/.test(s.eventDate)||isNaN(Date.parse(s.eventDate)))s.eventDate=nextThanksgiving();
 for(const k of ['count','customHeadcount','kids','customKids','estimatedDrinkers','customDrinkers','ovens','racks','tableCapacity'])s[k]=integer(s[k]);s.ovens=Math.max(1,Math.min(8,s.ovens));s.racks=Math.max(1,Math.min(8,s.racks));s.tableCapacity=Math.max(2,s.tableCapacity);s.schemaVersion=4;
 return reconcileState(s,catalog);
}
export function planningContext(s:State){const expected=s.guests.filter(g=>g.rsvp!=='Declined'),confirmed=s.guests.filter(g=>g.rsvp==='Attending'),list=s.planningMode==='Expected'||s.planningMode==='Confirmed',known=s.planningMode==='Confirmed'?confirmed:expected;const head=list?known.length:integer(s.planningMode==='Custom'?s.customHeadcount:s.count);const children=list?known.filter(g=>g.ageGroup==='Child').length:Math.min(head,integer(s.planningMode==='Custom'?s.customKids:s.kids));const adults=head-children;const drinkers=s.drink==='No-alcohol-forward'?0:list?known.filter(g=>g.ageGroup==='Adult'&&g.alcohol===true).length:Math.min(adults,integer(s.planningMode==='Custom'?s.customDrinkers:s.estimatedDrinkers));return{planningHeadcount:head,planningAdults:adults,planningChildren:children,planningAdultDrinkers:drinkers,foodPortions:(adults+children*.65)*(s.appetite==='Lighter'?.85:s.appetite==='Generous'?1.15:1),planningGuests:known,expectedCount:expected.length,confirmedCount:confirmed.length,listDrivenHeadcount:list,unknownGuestCount:Math.max(0,head-known.length)};}
export function responsibility(s:State,d:Pick<Dish,'id'>){return s.menuPlan[d.id] || {owner:'Host',status:'Confirmed' as const,preparation:s.easy.includes(d.id)?'Purchased' as const:'Homemade' as const};}
export function preparation(s:State,d:Pick<Dish,'id'>){const r=responsibility(s,d);const valid=r.owner==='Other'||s.guests.some(g=>g.guestId===r.owner&&g.rsvp!=='Declined');return r.owner!=='Host'&&valid&&r.status!=='Planned'?'Guest-provided':r.preparation;}
export function reconcileState(s:State,catalog:Dish[]){
 const all=[...catalog,...s.customRecipes],valid=new Set(all.map(d=>d.id));s={...s,selections:[...new Set(s.selections)].filter(id=>valid.has(id))};
 const active=new Set(s.selections);s.menuPlan=Object.fromEntries(Object.entries(s.menuPlan).filter(([id])=>active.has(id)));s.easy=s.selections.filter(id=>responsibility(s,{id}).preparation==='Purchased');
 const p=planningContext(s),seats=tableSeats(s,p),allowed=new Map(seats.map(x=>[x.id,x])),occupied=new Set<string>();const next:Record<string,string>={};
 for(const g of p.planningGuests.slice(0,p.planningHeadcount)){const id=s.seating[g.guestId],seat=allowed.get(id);if(seat&&!occupied.has(id)&&(!s.kidsTable||seat.kind===(g.ageGroup==='Child'?'kids':'main'))){next[g.guestId]=id;occupied.add(id);}}
 const working={...s,seating:next};const plan=derivePlan(working,all);
 const sourceKeys=new Set(derivePlan({...working,hiddenShopping:[]},all).shoppingEntries.map(x=>x.key));
 const activeTaskIds=new Set(buildTimeline(working,plan).map(r=>r[2]));const keepDone=(k:string)=>!(/^(menu-|oven-|guest-contribution-|timeline-|activity-)/.test(k))||activeTaskIds.has(k);
 const keepPrintable=(k:string)=>k==='menu'||k==='kids'&&p.planningChildren>0||k==='leftovers'&&s.leftovers||(/^guest-slot-\d+$/.test(k)&&Number(k.slice(11))<=p.unknownGuestCount)||(k.startsWith('guest-')?p.planningGuests.slice(0,p.planningHeadcount).some(g=>k==='guest-'+g.guestId):k.startsWith('dish-')?active.has(k.slice(5)):k.startsWith('activity-')?s.activities.includes(k.slice(9)):false);
 return {...working,done:s.done.filter(keepDone),purchased:s.purchased.filter(k=>sourceKeys.has(k)),shoppingOverrides:Object.fromEntries(Object.entries(s.shoppingOverrides).filter(([k])=>sourceKeys.has(k))),hiddenShopping:s.hiddenShopping.filter(k=>sourceKeys.has(k)),unitPrices:Object.fromEntries(Object.entries(s.unitPrices).filter(([k])=>sourceKeys.has(k))),timelineOverrides:Object.fromEntries(Object.entries(s.timelineOverrides).filter(([k])=>activeTaskIds.has(k))),printableOverrides:Object.fromEntries(Object.entries(s.printableOverrides).filter(([k])=>keepPrintable(k)))};
}
function tableSeats(s:State,p:ReturnType<typeof planningContext>){const kids=s.kidsTable?p.planningChildren:0,main=p.planningHeadcount-kids,capacity=Math.max(2,integer(s.tableCapacity,8));return [...Array.from({length:Math.ceil(main/capacity)},(_,i)=>({id:`main-${i+1}`,label:`Table ${i+1}`,capacity,kind:'main'})),...Array.from({length:Math.ceil(kids/6)},(_,i)=>({id:`kids-${i+1}`,label:`Kids table ${i+1}`,capacity:6,kind:'kids'}))].flatMap(t=>Array.from({length:t.capacity},(_,i)=>({id:`${t.id}:seat-${i+1}`,label:`${t.label} · seat ${i+1}`,kind:t.kind})));}
export const minutes=(v:string)=>{const [h,m]=v.split(':').map(Number);return h*60+m;};
export function dishPortions(s:State,d:Dish){const p=planningContext(s);if(!s.selections.includes(d.id))return 0;if(d.group==='Drink · Alcoholic')return p.planningAdultDrinkers;if(d.group==='Drink · Kids')return p.listDrivenHeadcount?Math.max(0,p.planningChildren-p.planningGuests.filter(g=>g.ageGroup==='Child'&&g.kidBeverage.trim()).length):0;if(d.group==='Drink · After dinner')return p.planningAdults;if(d.group.startsWith('Drink'))return p.planningHeadcount;return d.audience==='adults'?p.planningAdults:d.audience==='kids'?p.planningChildren:p.foodPortions;}
export function shoppingMeasure(quantity:number,unit:string):[number,string]{const u=unit.toLowerCase();if(['tbsp','tablespoon','tablespoons'].includes(u))return [quantity/16,'cup'];if(['tsp','teaspoon','teaspoons'].includes(u))return [quantity/48,'cup'];if(['cup','cups'].includes(u))return [quantity,'cup'];if(['lb','pound','pounds'].includes(u))return [quantity*16,'oz'];if(['ounce','ounces','oz'].includes(u))return [quantity,'oz'];return [quantity,unit];}
export const recipeReady=(d:Dish)=>d.group.startsWith('Drink')||Boolean(d.instructions?.trim()&&d.ingredients.length&&d.serves&&d.serves>0);
export function recipeQuantityServings(s:State,d:Dish){const target=dishPortions(s,d);if(!d.batchMode||!d.serves)return target;const step=d.batchMode==='half'?.5:1;return Math.ceil(target/d.serves/step)*step*d.serves;}
export function recipeIngredientQuantity(s:State,d:Dish,name:string,perServing:number){const amount=perServing*recipeQuantityServings(s,d),step=d.ingredientSteps?.[name];return step?Math.ceil(amount/step-1e-9)*step:amount;}
export function formatRecipeAmount(n:number){
 if(!Number.isFinite(n))return '—';if(n===0)return '0';
 const whole=Math.floor(n),part=n-whole;
 for(const denominator of [2,3,4,8,16]){const numerator=Math.round(part*denominator);if(numerator>0&&numerator<denominator&&Math.abs(part-numerator/denominator)<1e-6)return `${whole?whole+' ':''}${numerator}/${denominator}`;}
 return Number(n.toPrecision(6)).toString();
}
export function completeMealCoverage(required:string[],selected:Dish[],tagsFor:(dish:Dish)=>string[]){
 const compatible=selected.filter(d=>required.every(tag=>{
  const tags=tagsFor(d);return tags.includes(tag)||tag==='Vegetarian'&&tags.includes('Vegan')||(tag==='Dairy-Free'||tag==='Egg-Free')&&tags.includes('Vegan');
 }));
 return compatible.some(d=>d.group==='Main')&&compatible.filter(d=>['Starch','Fresh','Bread'].includes(d.group)).length>=2;
}
export function printableCards(s:State,p:ReturnType<typeof derivePlan>,tagsFor:(dish:Dish)=>string[]){
 const named=p.planningGuests.slice(0,p.planningHeadcount);
 const cards=[
  {id:'menu',name:'Dinner menu',desc:p.selected.filter(d=>!d.group.startsWith('Drink')).map(d=>d.name).join(' · ')},
  ...p.selected.map(d=>({id:'dish-'+d.id,name:(d.group.startsWith('Drink')?'Bar sign · ':'Food label · ')+d.name,desc:[d.group,...tagsFor(d)].join(' · ')})),
  ...named.map(g=>({id:'guest-'+g.guestId,name:g.name,desc:[p.seats.find(x=>x.id===s.seating[g.guestId])?.label,g.diet,g.note].filter(Boolean).join(' · ')||'Welcome'})),
  ...Array.from({length:p.unknownGuestCount},(_,i)=>({id:`guest-slot-${i+1}`,name:'Guest',desc:'Place card · add a name when your guest list is ready'})),
  ...s.activities.map(x=>({id:'activity-'+x,name:x,desc:'Good company. A little conversation.'})),
  ...(p.planningChildren?[{id:'kids',name:'Kids’ table',desc:`${p.planningChildren} children · ${s.childDrink}`}]:[]),
  ...(s.leftovers?[{id:'leftovers',name:'For tomorrow',desc:p.selected.filter(d=>!d.group.startsWith('Drink')).map(d=>d.name).join(' · ')}]:[])
 ];
 return cards.map(card=>({...card,...s.printableOverrides[card.id]}));
}
export function derivePlan(s:State,all:Dish[]){
 const p=planningContext(s),planningCount=p.planningHeadcount,kids=p.planningChildren,adults=p.planningAdults,adultDrinkers=p.planningAdultDrinkers,foodGuests=p.foodPortions,dinner=minutes(s.time),warnings:string[]=[];
 const selected=all.filter(d=>s.selections.includes(d.id)&&!(d.group==='Drink · Alcoholic'&&(s.drink==='No-alcohol-forward'||!adultDrinkers))).sort((a,b)=>s.selections.indexOf(a.id)-s.selections.indexOf(b.id));
 if(selected.some(d=>d.id==='turkey')&&selected.some(d=>d.id==='gravy'))warnings.push('The turkey recipe already includes gravy. Basic turkey gravy is an additional recipe; remove it unless you want extra.');
 const hostOwnedSelected=selected.filter(d=>preparation(s,d)!=='Guest-provided'),guestProvidedSelected=selected.filter(d=>preparation(s,d)==='Guest-provided'),incompleteRecipes=hostOwnedSelected.filter(d=>preparation(s,d)==='Homemade'&&!recipeReady(d)),hostPrepared=planningCount?hostOwnedSelected.filter(d=>preparation(s,d)==='Homemade'&&recipeReady(d)):[],purchasedDishes=planningCount?hostOwnedSelected.filter(d=>preparation(s,d)==='Purchased'):[];
 for(const d of incompleteRecipes)warnings.push(`${d.name}: complete the recipe before ingredients, budget and cooking tasks can be generated.`);
 for(const d of selected){const r=responsibility(s,d);if(r.owner!=='Host'&&preparation(s,d)!=='Guest-provided')warnings.push(`${d.name}: ${r.owner==='Other'?'other provider':s.guests.find(g=>g.guestId===r.owner)?.name || 'missing guest'} is unconfirmed or unavailable. Host fallback is included.`);}
 for(const g of p.planningGuests)if(g.dish.trim()&&!selected.some(d=>responsibility(s,d).owner===g.guestId))warnings.push(`${g.name}: link the previous contribution note “${g.dish}” to a menu item. It does not reduce host shopping yet.`);
 const turkeyDishes=hostPrepared.filter(d=>d.id==='turkey'||d.id==='ba-dry-turkey'||d.id==='guide-breast');const turkeyActive=!!turkeyDishes.length;const sourceTurkey=turkeyDishes.find(d=>d.recipeVerified);const bird=sourceTurkey?Math.ceil(dishPortions(s,sourceTurkey)/(sourceTurkey.serves||1))*(sourceTurkey.id==='guide-breast'?5:14):turkeyActive?Math.max(s.turkey==='Turkey breast'?4:10,Math.ceil(foodGuests*(s.turkey==='Turkey breast'?(s.leftovers?.85:.65):(s.leftovers?1.5:1.25))/2)*2):0;
 const birds=sourceTurkey?Math.ceil(dishPortions(s,sourceTurkey)/(sourceTurkey.serves||1)):bird>24?Math.ceil(bird/20):bird?1:0,birdEach=birds?Math.ceil(bird/birds):0,turkeyMinutes=sourceTurkey?sourceTurkey.oven:bird?birdEach*(s.turkey==='Turkey breast'?17:14):0;const thaw=new Date(s.eventDate+'T12:00:00');thaw.setDate(thaw.getDate()-Math.ceil(birdEach/4.5)-1);const thawText=thaw.toLocaleDateString('en-US',{month:'short',day:'numeric'});
 type Slot={dish:Dish;start:number;end:number;oven:number;racks:number;temp:number;stage?:string;taskId:string;batch:number};const allocated:Slot[]=[],conflicts:Slot[]=[];
 const jobs=hostPrepared.filter(d=>d.oven>0).map(d=>({dish:d,duration:d.recipeVerified?d.oven:turkeyDishes.includes(d)?turkeyMinutes:d.oven,temp:d.temp||350,racks:turkeyDishes.includes(d)&&!d.recipeVerified?birds:1,deadline:d.group==='Dessert'?dinner-1440+240:turkeyDishes.includes(d)?dinner-65:dinner-(d.group==='Appetizer'?65:15)-(d.restMinutes||0)}));
 for(const job of jobs.sort((a,b)=>(turkeyDishes.includes(b.dish)?1:0)-(turkeyDishes.includes(a.dish)?1:0)||b.duration-a.duration)){
  const batches=job.dish.batchMode==='whole'?Math.ceil(dishPortions(s,job.dish)/(job.dish.serves||1)):Math.max(1,job.dish.recipeVerified?Math.ceil(dishPortions(s,job.dish)/(job.dish.serves||1)):1);
  // Each source-size pan/bird gets its own reservation; ingredient scale never stretches cooking time.
  for(let batch=0;batch<batches;batch++){
   const stages:NonNullable<Dish['ovenStages']>=job.dish.ovenStages?.length?job.dish.ovenStages:[{label:'',minutes:job.duration,temp:job.temp}];let deadline=job.deadline;
   for(let stageIndex=stages.length-1;stageIndex>=0;stageIndex--){const stage=stages[stageIndex];let fit:Slot|undefined;const rackDemand=Math.min(job.racks,s.racks);const taskId=job.dish.id+(stages.length>1?'-stage-'+stageIndex:'')+(batch?'-batch-'+batch:'');
    if(job.racks>s.racks)warnings.push(`${job.dish.name}: more rack space is required; review the cooking source.`);
    for(let end=deadline;end>=deadline-720&&!fit;end-=5){const start=end-stage.minutes;for(let oven=1;oven<=s.ovens;oven++){
     const near=allocated.filter(a=>a.oven===oven&&start<a.end+15&&end+15>a.start),overlapping=near.filter(a=>start<a.end&&end>a.start);const tempBlocked=near.some(a=>a.temp!==stage.temp);let capacity=true;
     for(const t of [start,...overlapping.map(a=>Math.max(start,a.start))])if(rackDemand+overlapping.filter(a=>a.start<=t&&a.end>t).reduce((n,a)=>n+a.racks,0)>s.racks)capacity=false;
     if(!tempBlocked&&capacity){fit={dish:job.dish,start,end,oven,racks:rackDemand,temp:stage.temp,stage:stage.label,taskId,batch};break;}
    }}
    if(!fit){fit={dish:job.dish,start:deadline-stage.minutes,end:deadline,oven:1,racks:job.racks,temp:stage.temp,stage:stage.label,taskId,batch};conflicts.push(fit);}allocated.push(fit);
    // Leave preparation/cooling time between source steps, and time for changing oven temperature.
    deadline=fit.start-(stageIndex>0&&stages[stageIndex-1].temp!==stage.temp?15:0)-(stage.waitBefore||0);
   }
  }
 }
 for(const a of allocated){if(a.dish.group!=='Dessert'&&!turkeyDishes.includes(a.dish)&&a.end<dinner-120){conflicts.push(a);warnings.push(`${a.dish.name} finishes over two hours before dinner. Add safe hot holding or reschedule with another oven.`);}if(a.start<0&&a.dish.group!=='Dessert')warnings.push(`${a.dish.name} needs to start the previous day. Review the schedule.`);}
 const turkeySlot=allocated.find(x=>turkeyDishes.includes(x.dish));const schedule={slots:allocated.filter(x=>!turkeyDishes.includes(x.dish)||x.dish.recipeVerified).sort((a,b)=>a.start-b.start),turkeyIn:turkeySlot?.start??dinner,turkeyOut:turkeySlot?.end??dinner,conflicts,sideOven:jobs.filter(x=>!turkeyDishes.includes(x.dish)).map(x=>x.dish)};
 const tableCapacity=Math.max(2,s.tableCapacity),kidsAtOwnTable=s.kidsTable?kids:0,mainTableGuests=planningCount-kidsAtOwnTable,mainTableCount=Math.ceil(mainTableGuests/tableCapacity),kidsTableCount=Math.ceil(kidsAtOwnTable/6),totalTableCount=mainTableCount+kidsTableCount,chairNeed=s.service==='Cocktail-style'?Math.ceil(planningCount*.65):planningCount,buffer=(n:number)=>Math.ceil(n*1.1),dessert=selected.some(d=>d.group==='Dessert'),wine=selected.some(d=>d.group==='Drink · Alcoholic'&&/wine|sparkling/i.test(d.name)),cocktail=selected.some(d=>d.group==='Drink · Alcoholic'&&!/wine|sparkling/i.test(d.name)),coffee=selected.some(d=>d.group==='Drink · After dinner');
 const inventoryRows=[['chairs','Chairs',chairNeed],['tablesOwned','Tables',totalTableCount],['plates','Dinner plates',buffer(planningCount)],['dessertPlates','Dessert plates',dessert?buffer(planningCount):0],['forks','Dinner forks',buffer(planningCount)],['dessertForks','Dessert forks',dessert?buffer(planningCount):0],['spoons','Spoons',dessert||coffee?buffer(planningCount):0],['knives','Dinner knives',buffer(planningCount)],['waterGlasses','Water glasses',buffer(planningCount)],['glasses','Wine glasses',wine?buffer(adultDrinkers):0],['cocktailGlasses','Cocktail glasses',cocktail?buffer(adultDrinkers):0],['adultCups','Adult cups',buffer(adults)],['coffeeMugs','Coffee mugs',coffee?buffer(adults):0],['kidsCups','Kids’ cups',buffer(kids)],['napkins','Dinner napkins',buffer(planningCount)],['linens','Table linens',totalTableCount],['platters','Serving pieces',planningCount?selected.filter(d=>!d.group.startsWith('Drink')).length:0]].map(([key,label,need])=>({key:key as keyof State,label:String(label),need:Number(need),have:num(s[key as keyof State]),missing:Math.max(0,Number(need)-num(s[key as keyof State])),unit:'each'}));
 const rows=new Map<string,{key:string;name:string;count:number;unit:string;category:string;auto:boolean;id?:string;cost:number;source:string}>();
 const add=(name:string,count:number,unit:string,category:string,cost=0,source='Menu')=>{if(!count)return;const key=`auto:${category}:${name}:${unit}`,old=rows.get(key);rows.set(key,{key,name,count:(old?.count||0)+count,unit,category,auto:true,cost:(old?.cost||0)+cost,source:old&&old.source!==source?old.source+' + '+source:source});};
 for(const d of hostOwnedSelected){if(!planningCount)continue;const target=preparation(s,d)==='Purchased'?dishPortions(s,d):recipeQuantityServings(s,d);if(preparation(s,d)==='Homemade'&&!recipeReady(d))continue;const cost=(preparation(s,d)==='Purchased'?d.easyCost:d.cost)*target/18;if(preparation(s,d)==='Purchased'){add(d.easier||`Prepared ${d.name}`,target,'servings',d.group.startsWith('Drink')?'Beverages':'Bakery',cost,d.name);continue;}d.ingredients.forEach(([name,n,unit,category])=>{const [q,u]=shoppingMeasure(turkeyDishes.includes(d)&&!d.recipeVerified&&/turkey/i.test(name)?bird:recipeIngredientQuantity(s,d,name,n),unit);add(name,q,u,category,cost/Math.max(1,d.ingredients.length),d.name);});}
 if(planningCount){add('Low seasonal florals',totalTableCount,'arrangements','Florals',totalTableCount*25,'Table');add('Dinner candles',totalTableCount*4,'each','Tabletop',totalTableCount*12,'Table');
  const essentials:[string,number,string,string][]=[['Toilet paper',Math.ceil(planningCount/5),'rolls','Hosting'],['Paper towels',Math.ceil(planningCount/10),'rolls','Hosting'],['Dish soap',1,'bottle','Hosting'],['Hand soap',1,'bottle','Hosting'],['Dishwasher pods',Math.ceil(planningCount/4),'pods','Hosting'],['Trash bags',Math.ceil(planningCount/4),'bags','Hosting'],['Foil',hostPrepared.length?1:0,'roll','Hosting'],['Plastic wrap',hostPrepared.length?1:0,'roll','Hosting'],['Leftover containers',s.leftovers?Math.ceil(planningCount/2):0,'containers','Hosting'],['Ice',Math.ceil(planningCount*1.5),'lb','Beverages'],['Cleaning spray',1,'bottle','Hosting'],['Matches / lighter',1,'each','Hosting'],['Batteries',1,'pack','Hosting']];
  if(coffee)essentials.push(['Coffee filters',1,'pack','Beverages']);if(s.outdoor)essentials.push(['Covered serving trays',Math.max(1,selected.length),'each','Hosting'],['Outdoor lighting',1,'set','Hosting'],['Cooler ice',Math.ceil(planningCount),'lb','Hosting']);if(s.location!=='At home')essentials.push(['Transport containers',selected.length,'each','Hosting']);for(const [name,n,u,c] of essentials)add(name,n,u,c,n*2,'Hosting rule');
  const preferences=new Map<string,number>();if(p.listDrivenHeadcount)p.planningGuests.filter(g=>g.ageGroup==='Child'&&g.kidBeverage.trim()).forEach(g=>preferences.set(g.kidBeverage.trim(),(preferences.get(g.kidBeverage.trim())||0)+1));else if(kids)preferences.set(s.childDrink,kids);for(const [name,n] of preferences)add(name,n*2,'servings','Beverages',n*2,'Child preferences');
 }
 for(const r of inventoryRows)if(r.missing)add(r.label,r.missing,r.unit,'Tabletop',r.missing*(r.key==='chairs'?12:r.key==='tablesOwned'?22:3),'Inventory');
 const automatic=[...rows.values()],manual=s.customShoppingItems.map(i=>({key:`custom:${i.id}`,name:i.name,count:i.quantity,unit:i.unit,category:i.category,auto:false,id:i.id,cost:0,source:'Manual'}));
 const shoppingEntries=[...automatic,...manual].filter(r=>!s.hiddenShopping.includes(r.key));let planned=0;for(const r of shoppingEntries){const o=s.shoppingOverrides[r.key],q=Math.max(0,o?o.mode==='locked'?o.value:r.count+o.value:r.count);if(q<r.count)warnings.push(`${r.name}: planned ${q} ${r.unit}, automatic requirement ${Math.ceil(r.count*10)/10}. Review the shortfall.`);planned+=q*(s.unitPrices[r.key]??(r.count?r.cost/r.count:0));}
 const estimates:Record<string,number>={};for(const r of automatic)estimates[r.category]=(estimates[r.category]||0)+r.cost;const estimated=Object.values(estimates).reduce((a,b)=>a+b,0),actual=s.actualSpend.reduce((a,b)=>a+b.amount,0);
 const cold=hostOwnedSelected.reduce((n,d)=>n+(d.group==='Main'?3:d.group==='Dessert'?2:1),0)*(planningCount?1:0),capacity=(s.fridge==='Tight'||s.fridge==='Limited')?8:s.fridge==='Generous'?28:16;if(cold>capacity)warnings.push(`Refrigerator space: about ${cold} storage units for ${capacity} available. Stage deliveries or arrange extra cold storage.`);
 if(s.outdoor&&planningCount)warnings.push('Outdoor service: check weather fallback, lighting and hot/cold holding.');if(p.listDrivenHeadcount&&p.planningGuests.some(g=>g.ageGroup==='Adult'&&g.alcohol===null))warnings.push('Some alcohol preferences are unanswered. Only explicit yes responses count toward alcohol.');if(p.planningGuests.length>planningCount)warnings.push('Your named guest list exceeds the selected headcount. Review the planning mode before seating.');if(inventoryRows.some(r=>r.missing))warnings.push('Inventory still needs: '+inventoryRows.filter(r=>r.missing).map(r=>`${r.missing} ${r.label.toLowerCase()}`).join(', '));
 const hostStart=minutes(s.hostBuffer);if(allocated.some(x=>x.start>=hostStart&&x.start<hostStart+45))warnings.push('A cooking task starts during your 45-minute get-ready window. Move the host window or review the cooking schedule.');
 const unpricedRecipes=hostPrepared.filter(d=>d.recipeVerified&&d.ingredients.some(([name,,unit,category])=>{const u=shoppingMeasure(1,unit)[1];return s.unitPrices[`auto:${category}:${name}:${u}`]===undefined;}));if(unpricedRecipes.length)warnings.push('Budget incomplete: enter ingredient unit prices for '+unpricedRecipes.map(d=>d.name).join(' · '));
 return {...p,selected,hostOwnedSelected,guestProvidedSelected,hostPrepared,purchasedDishes,incompleteRecipes,unpricedRecipes,planningCount,kids,adults,adultDrinkers,foodGuests,dinner,bird,turkeyActive,turkeyMinutes,thawText,schedule,tableSeats:tableCapacity,mainTableCount,kidsTableCount,totalTableCount,linenCount:totalTableCount,mainTableGuests,kidsAtOwnTable,chairNeed,inventoryRows,missing:inventoryRows.map(r=>[r.label,r.missing] as [string,number]),estimates,estimated,planned,actual,shoppingEntries,seats:tableSeats(s,p),warnings};
}
export function buildTimeline(s:State,p:ReturnType<typeof derivePlan>):[number,string,string][]{
 const T=p.dinner,rows:[number,string,string][]=[];const add=(t:number,label:string,id:string)=>rows.push([t+(s.timelineOverrides[id]||0),label,id]);if(!p.planningCount)return s.customTimelineItems.map(x=>[minutes(x.time),`${x.category} · ${x.label}`,x.id]);
 add(T-210,'Final house reset · entry, bathroom and guest areas','house-reset');add(T-180,'Empty dishwasher and clear sink','kitchen-reset');add(T-120,'Stage and label serving pieces','serving-labels');
 if(p.turkeyActive&&!p.hostPrepared.some(d=>d.recipeVerified&&(d.id==='turkey'||d.id==='ba-dry-turkey'||d.id==='guide-breast'))){add(p.schedule.turkeyIn-30,'Prepare turkey for roasting','turkey-prepare');add(p.schedule.turkeyIn,`Turkey into oven · ${p.bird} lb total`,'turkey-in');add(p.schedule.turkeyOut,'Check turkey with thermometer; rest','turkey-rest');add(T-25,'Carve turkey','carve');}
 if(p.turkeyActive&&p.hostPrepared.some(d=>d.recipeVerified&&(d.id==='turkey'||d.id==='ba-dry-turkey'||d.id==='guide-breast')))add(T-25,'Carve turkey','carve');
 for(const x of p.schedule.slots){const label=`${x.dish.name}${x.stage?' · '+x.stage:''}${x.batch?' · batch '+(x.batch+1):''}`;const sourceStage=x.dish.ovenStages?.find(stage=>stage.label===x.stage);if(sourceStage?.waitBefore)add(x.start-sourceStage.waitBefore,`Prepare between stages · ${label}`,'recipe-assembly-'+x.taskId);add(x.start,`${label} into oven ${x.oven} · ${x.temp}°F`,'oven-'+x.taskId);add(x.end,`${label} out of oven`,'oven-out-'+x.taskId);if(x.dish.prepMinutes&&(!x.dish.ovenStages?.length||x.taskId.includes('-stage-0')))add(x.start-x.dish.prepMinutes,`Prepare ${label}`,'recipe-prep-'+x.taskId);const rest=sourceStage?.restAfter||((!x.dish.ovenStages?.length||x.taskId.includes('-stage-'+(x.dish.ovenStages.length-1)))?x.dish.restMinutes||0:0);if(rest)add(x.end+rest,`Cooling / resting complete · ${label}`,'recipe-rest-'+x.taskId);}
 for(const d of p.selected){const mode=preparation(s,d);if(mode==='Homemade'&&(d.oven>0||!recipeReady(d)))continue;const r=responsibility(s,d),owner=s.guests.find(g=>g.guestId===r.owner)?.name||'provider';const when=d.group==='Dessert'?T+75:d.group==='Appetizer'?T-65:d.group.startsWith('Drink')?T-75:T-30;if(mode==='Homemade'){const rest=d.restMinutes||0,prep=d.prepMinutes||d.minutes;add(when-prep-rest,`Start preparation · ${d.name}`,'recipe-prep-'+d.id);if(rest){add(when-rest,`Cooking complete; begin cooling / resting · ${d.name}`,'recipe-cook-'+d.id);add(when,`Cooling / resting complete · ${d.name}`,'recipe-rest-'+d.id);}}add(when,mode==='Guest-provided'?`Receive ${d.name} from ${owner}`:mode==='Purchased'?`Receive / stage prepared ${d.name}`:`Prepare / serve ${d.name}`,'menu-'+d.id);}
 add(minutes(s.hostBuffer),'Get ready · protect 45 minutes for yourself','host-ready');add(T-60,'Welcome guests · drinks, coats and bathroom','arrival');add(T-15,'Transfer food and finish the serving area','serve-transfer');add(T,'Dinner is served','dinner');s.activities.forEach((x,i)=>add(T+(x==='After-dinner game'?115:20+i*15),x,'activity-'+x));if(p.selected.some(x=>x.group==='Dessert'))add(T+65,'Set up dessert and coffee service','dessert-service');add(T+110,'Refrigerate perishables; label leftovers','cleanup');
 for(const t of s.customPrepTasks)if(t.phase==='THANKSGIVING DAY'||t.phase==='FINAL 60 MINUTES')add(T-(t.phase==='THANKSGIVING DAY'?180:50),t.label,'timeline-'+t.id);for(const t of s.customTimelineItems)add(minutes(t.time),`${t.category} · ${t.label}`,t.id);
 return rows.sort((a,b)=>a[0]-b[0]);
}
export function parseIngredients(value:string,serves:number):Dish['ingredients']{return value.split('\n').filter(x=>x.trim()).map(line=>{const [name,q,unit,category='Custom']=line.split('|').map(x=>x.trim());if(!name||!q||!Number.isFinite(Number(q))||Number(q)<=0||!unit)throw new Error('Use one ingredient per line: name | quantity | unit | category. Quantities must be positive numbers.');return [name,Number(q)/serves,unit,category] as [string,number,string,string];});}
export function printOne(card:{name:string;desc:string}){const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='0';frame.style.height='0';frame.style.border='0';document.body.append(frame);const doc=frame.contentDocument!;doc.open();doc.write('<!doctype html><html><head><title>Printable</title><style>@page{size:letter;margin:1in}body{font:18px Georgia;color:#181818}.card{border:1px solid #aaa;padding:.5in;max-width:5in;min-height:3in}h1{font-weight:normal;font-size:28px}small{font:11px Arial;letter-spacing:3px}p{line-height:1.7}</style></head><body><div class="card"><small>CROW &amp; CROWN</small><h1></h1><p></p></div></body></html>');doc.close();doc.querySelector('h1')!.textContent=card.name;doc.querySelector('p')!.textContent=card.desc;frame.contentWindow!.focus();frame.contentWindow!.print();setTimeout(()=>frame.remove(),60000);}

export function timelineWarnings(s:State,p:ReturnType<typeof derivePlan>){const rows=buildTimeline(s,p),by=new Map(rows.map(r=>[r[2],r]));const edges:[string,string][]=p.turkeyActive?[['turkey-prepare','turkey-in'],['turkey-in','turkey-rest'],['turkey-rest','carve'],['carve','dinner']]:[];for(const slot of p.schedule.slots){if(slot.dish.ovenStages?.length){const index=slot.dish.ovenStages.findIndex(x=>x.label===slot.stage);if(index>0){const previous=slot.taskId.replace('-stage-'+index,'-stage-'+(index-1));edges.push(['oven-out-'+previous,'oven-'+slot.taskId]);}}edges.push(['oven-'+slot.taskId,'oven-out-'+slot.taskId],['oven-out-'+slot.taskId,'dinner'],['recipe-prep-'+slot.taskId,'oven-'+slot.taskId],['recipe-rest-'+slot.taskId,'dinner']);if((slot.dish.id==='turkey'||slot.dish.id==='guide-breast')&&slot.dish.recipeVerified)edges.push(['oven-out-'+slot.taskId,'recipe-rest-'+slot.taskId],['recipe-rest-'+slot.taskId,'carve']);}for(const d of p.hostPrepared.filter(x=>!x.oven))edges.push(['recipe-prep-'+d.id,'recipe-cook-'+d.id],['recipe-cook-'+d.id,'recipe-rest-'+d.id],['recipe-rest-'+d.id,'menu-'+d.id]);edges.push(['arrival','dinner'],['dinner','cleanup']);return edges.filter(([a,b])=>by.has(a)&&by.has(b)&&by.get(a)![0]>by.get(b)![0]).map(([a,b])=>`Schedule conflict: ${by.get(a)![1]} is after ${by.get(b)![1]}. Reset the time adjustment or change the plan.`);}
