import type { Dish } from './App';
// Direct publisher batch measurements, normalized once for the shared quantity engine.
// Short original planning summaries; the full linked recipe remains authoritative.
const add=(id:string,name:string,group:string,serves:number,source:string,url:string,rating:string,ingredients:Dish['ingredients'],instructions:string,extra:Partial<Dish>):Dish=>({id:'expanded-'+id,name,group,serves,source,sourceUrl:url,rating,recipeVerified:true,style:'reader-favorite',minutes:0,oven:0,temp:0,cost:0,easyCost:0,portion:'One portion per guest',vessel:'Serving dish + utensil',easier:`Prepared ${name}`,makeAhead:'Prepare ingredients ahead; cook near service.',finish:'Serve as directed in the original recipe.',seasoning:'Check ingredient labels; pantry seasoning as needed.',tags:[],ingredients:ingredients.map(([n,q,u,c])=>[n,q/serves,u,c]),instructions,...extra});
const ar='https://www.allrecipes.com/recipe/';
const chef='https://www.onceuponachef.com/recipes/';
const veg=['Vegetarian','Gluten-Free','Egg-Free','Nut-Free'];
export const expandedRecipes:Dish[]=[
add('deviled-eggs','Classic deviled eggs','Appetizer',6,'Allrecipes',ar+'222589/simple-deviled-eggs/','4.5 ★ · 372 ratings',[
 ['Eggs',6,'each','Dairy'],['Mayonnaise',2,'tbsp','Pantry'],['Sugar',1,'tsp','Pantry'],['White vinegar',1,'tsp','Pantry'],['Yellow mustard',1,'tsp','Pantry'],['Onions',1,'tbsp','Produce'],['Celery',1,'tbsp','Produce'],['Salt',.5,'tsp','Pantry']],
 'Hard-boil, cool and peel eggs first. Halve; mash yolks with mayonnaise, mustard, vinegar, sugar, minced vegetables and salt. Fill whites, dust with paprika and refrigerate until serving.',
 {sourceYield:'12 halves; 6 appetizer portions of 2',minutes:65,prepMinutes:65,batchMode:'whole',portion:'2 egg halves per guest',vessel:'Saucepan + egg platter',tags:['Vegetarian','Gluten-Free','Dairy-Free','Nut-Free'],makeAhead:'Boil eggs and store filling and whites separately up to 2 days ahead; assemble near service.',seasoning:'Paprika to taste. Source starts with already-boiled eggs (15 min); planner allows another 50 min for boiling/cooling.'}),
add('spinach-dip','Hot spinach + artichoke dip','Appetizer',12,'Allrecipes',ar+'26819/hot-artichoke-and-spinach-dip-ii/','4.7 ★ · 3,249 ratings',[
 ['Cream cheese',8,'oz','Dairy'],['Mayonnaise',.25,'cup','Pantry'],['Parmesan',.25,'cup','Dairy'],['Romano cheese',.25,'cup','Dairy'],['Garlic',1,'clove','Produce'],['Dried basil',.5,'tsp','Pantry'],['Garlic salt',.25,'tsp','Pantry'],['Artichoke hearts',1,'14 oz can','Pantry'],['Frozen chopped spinach',.5,'cup','Frozen'],['Mozzarella',.25,'cup','Dairy']],
 'Mix softened cream cheese with mayonnaise, grated cheeses, garlic and seasonings. Fold in drained artichokes and thawed, squeezed spinach. Transfer to a greased small baker, top with mozzarella and bake at 350°F for 25 minutes.',
 {sourceYield:'12 dip portions; dippers separate',minutes:40,prepMinutes:15,oven:25,temp:350,batchMode:'whole',tags:['Gluten-Free','Nut-Free'],vessel:'Small baking dish',makeAhead:'Mix and refrigerate up to 2 days ahead; bake near arrival.',seasoning:'Salt, pepper and pan grease; add crackers, bread or vegetables separately to shopping. Mayonnaise contains eggs; traditional hard cheeses may use animal rennet.'}),
add('soup','Butternut squash soup','Appetizer',6,'Once Upon a Chef',chef+'butternut-squash-soup.html','4.65 ★ · 188 votes',[
 ['Butternut squash',2.5,'lb','Produce'],['Red bell pepper',1,'each','Produce'],['Onions',1,'each','Produce'],['Garlic',3,'clove','Produce'],['Water',7,'cup','Kitchen'],['Salt',1,'tbsp','Pantry'],['Sugar',2,'tbsp','Pantry'],['Heavy cream',.75,'cup','Dairy'],['Thyme',1,'tsp','Produce']],
 'Simmer squash, pepper, onion and garlic with water, salt and sugar, covered, for 35 minutes. Purée safely with an immersion blender. Stir in cream, heat gently and finish with thyme.',
 {sourceYield:'6–8 bowls; planned as 6 generous starter bowls',minutes:50,prepMinutes:50,tags:veg,vessel:'Large soup pot + immersion blender',makeAhead:'Refrigerate up to 3 days ahead; reheat on the stove. Freeze without the cream.',seasoning:'Optional extra cream or garnishes are separate. Use fresh squash, measured by weight.'}),
add('ham','Honey-glazed ham','Main',15,'Allrecipes',ar+'14745/honey-glazed-ham/','4.8 ★ · 1,464 ratings',[
 ['Fully cooked ham',1,'5 lb ham','Meat'],['Whole cloves',.25,'cup','Pantry'],['Honey',2,'cup','Pantry'],['Butter',2/3,'cup','Dairy'],['Dark corn syrup',.25,'cup','Pantry']],
 'Score and clove-stud a ready-to-eat ham. Warm honey, butter and syrup into a glaze. Bake at 325°F for 75 minutes, basting every 10–15 minutes; use the broiler for the final 4–5 minutes to caramelize. Rest briefly and slice.',
 {sourceYield:'One 5 lb fully cooked ham; 15 portions',minutes:100,prepMinutes:20,oven:75,temp:325,restMinutes:5,batchMode:'whole',tags:['Gluten-Free','Egg-Free','Nut-Free'],vessel:'Foil-lined roasting pan',makeAhead:'Buy a ready-to-eat ham; follow its label for warming requirements.',seasoning:'Whole cloves as needed. Final broiling occupies the same reserved oven slot; actual broiler setting is appliance-specific.'}),
add('sweet-casserole','Sweet potato + pecan casserole','Starch',12,'Allrecipes',ar+'21261/yummy-sweet-potato-casserole/','4.8 ★ · 4,227 ratings',[
 ['Sweet potatoes',4,'cup','Produce'],['Eggs',2,'each','Dairy'],['Sugar',.5,'cup','Pantry'],['Milk',.5,'cup','Dairy'],['Butter',7,'tbsp','Dairy'],['Vanilla extract',.5,'tsp','Pantry'],['Salt',.5,'tsp','Pantry'],['Brown sugar',.5,'cup','Pantry'],['Flour',1/3,'cup','Pantry'],['Pecans',.5,'cup','Pantry']],
 'Boil peeled sweet potato cubes until tender, then mash with eggs, sugar, milk, four tablespoons butter, vanilla and salt. Spread in a 9 × 13 inch baker. Crumble remaining butter with flour, brown sugar and pecans over it; bake 325°F for 30 minutes.',
 {sourceYield:'12 side portions; one 9 × 13 inch casserole',minutes:60,prepMinutes:30,oven:30,temp:325,batchMode:'whole',tags:['Vegetarian'],vessel:'9 × 13 inch baker + saucepan',makeAhead:'Keep filling and topping separately refrigerated up to 2 days ahead; assemble before baking.',seasoning:'Sweet potatoes measured peeled/cubed; publisher suggests approximately 2½ lb whole potatoes. Butter: 4 tbsp filling + 3 tbsp topping. Contains pecans, eggs, wheat and dairy.'}),
add('cauliflower','Garlic + Parmesan cauliflower','Fresh',6,'Allrecipes',ar+'54675/roasted-garlic-cauliflower/','4.6 ★ · 3,272 ratings',[
 ['Olive oil',3,'tbsp','Pantry'],['Garlic',2,'tbsp','Produce'],['Cauliflower',1,'large head','Produce'],['Parmesan',1/3,'cup','Dairy'],['Parsley',1,'tbsp','Produce']],
 'Coat cauliflower florets in oil and minced garlic. Roast in a greased 9 × 13 inch dish at 450°F for 25 minutes, stirring halfway. Add Parmesan and parsley, then broil for 3–5 minutes until browned.',
 {sourceYield:'6 side portions',minutes:45,prepMinutes:15,oven:30,temp:450,tags:['Gluten-Free','Egg-Free','Nut-Free'],vessel:'9 × 13 inch baker',seasoning:'Salt, pepper and pan grease. Reserved slot includes final broiling; actual broiler setting is appliance-specific.'}),
add('spinach','Lemon + nutmeg creamed spinach','Fresh',6,'Allrecipes',ar+'234938/fast-and-easy-creamed-spinach/','4.8 ★ · 266 ratings',[
 ['Olive oil',2,'tsp','Pantry'],['Spinach',32,'oz','Produce'],['Butter',1,'tbsp','Dairy'],['Shallots',2,'tbsp','Produce'],['Heavy cream',.75,'cup','Dairy'],['Lemon zest',1,'tsp','Produce'],['Parmesan',2,'tbsp','Dairy']],
 'Wilt spinach, drain, squeeze dry and chop. Soften shallot in butter; add seasonings and cream and reduce by half. Stir in lemon zest, spinach and Parmesan, warming gently until coated.',
 {sourceYield:'6 side portions',minutes:35,prepMinutes:35,tags:['Gluten-Free','Egg-Free','Nut-Free'],vessel:'Large pot + skillet',seasoning:'Pinches of cayenne, nutmeg, salt and pepper; optional source Parmesan is included. Traditional Parmesan may contain animal rennet.'}),
add('almondine','Green beans almondine','Fresh',8,'Mel’s Kitchen Cafe','https://www.melskitchencafe.com/easy-green-beans-almondine/','5 ★ · 11 ratings',[
 ['Water',1,'cup','Kitchen'],['Salt',1,'tsp','Pantry'],['Green beans',1,'lb','Produce'],['Butter',3,'tbsp','Dairy'],['Shallots',.25,'cup','Produce'],['Garlic',3,'clove','Produce'],['Brown sugar',1,'tsp','Pantry'],['Sliced almonds',.5,'cup','Pantry'],['Lemon juice',1,'tbsp','Produce']],
 'Steam beans in salted water for 4–5 minutes; drain. Melt butter in the same skillet, soften shallot and garlic, then toast almonds with sugar for 2–3 minutes. Toss beans back in and finish with lemon.',
 {sourceYield:'8 small side portions',minutes:35,prepMinutes:35,tags:['Vegetarian','Gluten-Free','Egg-Free'],vessel:'12 inch skillet',seasoning:'Uses publisher-supported water option. Optional sugar and lemon included. Contains almonds and dairy; not nut-free.'}),
add('rice-salad','Wild rice + cranberry apple salad','Starch',6,'Once Upon a Chef',chef+'wild-rice-salad-with-dried-cranberries-apples-orange-vinaigrette.html','5 ★ · 18 votes',[
 ['Wild rice',1,'cup','Pantry'],['Water',4,'cup','Kitchen'],['Salt',1.25,'tsp','Pantry'],['Orange zest',.5,'tsp','Produce'],['Orange juice',.25,'cup','Beverages'],['Olive oil',.25,'cup','Pantry'],['Apple cider vinegar',3,'tbsp','Pantry'],['Honey',2,'tbsp','Pantry'],['Dijon mustard',1,'tsp','Pantry'],['Black pepper',.25,'tsp','Pantry'],['Pecans',1,'cup','Pantry'],['Dried cranberries',.5,'cup','Pantry'],['Parsley',.5,'cup','Produce'],['Celery',2,'stalk','Produce'],['Apples',1,'each','Produce'],['Roasted pepitas',.25,'cup','Pantry'],['Scallions',2,'each','Produce']],
 'Simmer rice in salted water for 50–60 minutes, drain and cool. Toast pecans at 350°F for 6–10 minutes. Whisk citrus vinaigrette; toss cooled rice with nuts, fruit, vegetables, herbs and pepitas. Serve chilled or at room temperature.',
 {sourceYield:'6 side portions',minutes:100,prepMinutes:90,oven:10,temp:350,tags:['Vegetarian','Gluten-Free','Dairy-Free','Egg-Free'],vessel:'Saucepan + small tray + salad bowl',makeAhead:'Make and refrigerate one day ahead.',seasoning:'Contains pecans. Honey means this version is not vegan. Conservative planning reserves rice cooling plus nut-toasting time.'}),
add('muffins','Honey cornbread muffins','Bread',12,'Once Upon a Chef',chef+'cornbread-muffins.html','4.83 ★ · 594 votes',[
 ['Flour',1.25,'cup','Pantry'],['Cornmeal',.75,'cup','Pantry'],['Sugar',.375,'cup','Pantry'],['Baking powder',1,'tbsp','Pantry'],['Salt',1,'tsp','Pantry'],['Eggs',2,'each','Dairy'],['Honey',2,'tbsp','Pantry'],['Milk',.75,'cup','Dairy'],['Butter',.5,'cup','Dairy']],
 'Combine eggs, honey and milk. Separately whisk dry ingredients, then mix in liquids and cooled melted butter only until combined. Fill twelve muffin cups three-quarters full. Bake 350°F for 17–20 minutes; cool briefly.',
 {sourceYield:'12 muffins; one per portion',minutes:35,prepMinutes:10,oven:20,temp:350,restMinutes:5,batchMode:'whole',tags:['Vegetarian','Nut-Free'],kidFriendly:true,vessel:'12 cup muffin pan',makeAhead:'Best freshly baked; store airtight after cooling.',seasoning:'Cooking spray or muffin liners. Contains eggs, wheat and dairy.'}),
add('cranberry-bread','Cranberry orange + walnut bread','Bread',12,'Once Upon a Chef',chef+'cranberry-nut-bread.html','4.87 ★ · 260 votes',[
 ['Buttermilk',2/3,'cup','Dairy'],['Orange zest',2,'tsp','Produce'],['Orange juice',1/3,'cup','Beverages'],['Butter',6,'tbsp','Dairy'],['Eggs',1,'each','Dairy'],['Flour',2,'cup','Pantry'],['Sugar',1.125,'cup','Pantry'],['Salt',.75,'tsp','Pantry'],['Cinnamon',1,'tsp','Pantry'],['Baking powder',1,'tsp','Pantry'],['Baking soda',.25,'tsp','Pantry'],['Cranberries',1,'cup','Produce'],['Walnuts',.5,'cup','Pantry']],
 'Combine wet ingredients and dry ingredients separately, then fold together with halved cranberries and walnuts. Bake in a greased 9 × 5 inch loaf pan: 20 minutes at 375°F, then about 45 at 350°F. Cool ten minutes in pan and at least thirty on a rack.',
 {sourceYield:'One 9 × 5 inch loaf; about 12 slices',minutes:120,prepMinutes:15,oven:65,temp:350,restMinutes:40,batchMode:'whole',ovenStages:[{label:'Start loaf',minutes:20,temp:375},{label:'Finish loaf',minutes:45,temp:350}],tags:['Vegetarian'],vessel:'9 × 5 inch loaf pan',makeAhead:'Bake ahead and cool fully; freezes up to 3 months.',seasoning:'Pan grease; contains walnuts, eggs, wheat and dairy. Planner includes full source cooling, beyond the headline time.'}),
add('apple-crisp','Apple + oat crisp','Dessert',12,'Allrecipes',ar+'12409/apple-crisp-ii/','4.8 ★ · 7,919 ratings',[
 ['Apples',10,'cup','Produce'],['Sugar',1,'cup','Pantry'],['Flour',1+1/16,'cup','Pantry'],['Cinnamon',1,'tsp','Pantry'],['Water',3,'tbsp','Kitchen'],['Quick oats',1,'cup','Pantry'],['Brown sugar',1,'cup','Pantry'],['Baking powder',.25,'tsp','Pantry'],['Baking soda',.25,'tsp','Pantry'],['Butter',.5,'cup','Dairy']],
 'Toss sliced peeled apples with sugar, one tablespoon flour and cinnamon in a 9 × 13 inch baker; add water. Mix oats, remaining flour, brown sugar, leaveners and melted butter into crumbs. Scatter over apples; bake 350°F for about 45 minutes.',
 {sourceYield:'12 portions; one 9 × 13 inch crisp',minutes:75,prepMinutes:30,oven:45,temp:350,batchMode:'whole',tags:['Vegetarian','Egg-Free','Nut-Free'],kidFriendly:true,vessel:'9 × 13 inch baker',seasoning:'Apples measured peeled/sliced. Flour total: 1 cup topping + 1 tbsp filling. Ice cream is optional and separate.'}),
add('bread-pudding','Cinnamon vanilla bread pudding','Dessert',12,'Allrecipes',ar+'7177/bread-pudding-ii/','4.8 ★ · 4,461 ratings',[
 ['Day-old bread',6,'slice','Bakery'],['Butter',2,'tbsp','Dairy'],['Raisins',.5,'cup','Pantry'],['Milk',2,'cup','Dairy'],['Sugar',.75,'cup','Pantry'],['Eggs',4,'each','Dairy'],['Cinnamon',1,'tsp','Pantry'],['Vanilla extract',1,'tsp','Pantry']],
 'Tear bread into an 8 inch square baker and drizzle with butter; add raisins. Whisk remaining ingredients into custard, pour over bread and press gently to soak. Bake at 350°F for about 45 minutes until set.',
 {sourceYield:'12 small portions; one 8 inch square pan',minutes:60,prepMinutes:15,oven:45,temp:350,batchMode:'whole',tags:['Vegetarian','Nut-Free'],vessel:'8 inch square baker',makeAhead:'Bake a day ahead and refrigerate; reheat before serving.',seasoning:'Optional source raisins included; contains eggs, wheat and dairy.'}),
add('cheesecake','Double-layer pumpkin cheesecake','Dessert',8,'Allrecipes',ar+'13477/double-layer-pumpkin-cheesecake/','4.8 ★ · 3,994 ratings',[
 ['Cream cheese',16,'oz','Dairy'],['Sugar',.5,'cup','Pantry'],['Vanilla extract',.5,'tsp','Pantry'],['Eggs',2,'each','Dairy'],['Graham cracker crust',1,'9 inch crust','Bakery'],['Pumpkin puree',.5,'cup','Pantry'],['Cinnamon',.5,'tsp','Pantry']],
 'Beat cream cheese, sugar and vanilla; mix in eggs one at a time. Spread one cup plain batter in the crust. Add pumpkin and spices to remaining batter and layer above. Bake 325°F for 35–40 minutes; cool to room temperature for 1–2 hours, then chill at least three hours.',
 {sourceYield:'One 9 inch cheesecake; 8 slices',minutes:360,prepMinutes:20,oven:40,temp:325,restMinutes:300,batchMode:'whole',tags:['Vegetarian','Nut-Free'],vessel:'9 inch graham crust + refrigerator space',makeAhead:'Bake the day before; refrigerate overnight.',seasoning:'Pinches of ground cloves and nutmeg; optional whipped cream separate. Includes maximum stated cooling plus minimum chilling.'}),
add('mousse','Chocolate mousse cups','Dessert',6,'Once Upon a Chef',chef+'chocolate-mousse.html','4.58 ★ · 145 votes',[
 ['Butter',3,'tbsp','Dairy'],['Semisweet chocolate',6,'oz','Pantry'],['Pasteurized eggs',3,'each','Dairy'],['Cream of tartar',.5,'tsp','Pantry'],['Sugar',.375+2/48,'cup','Pantry'],['Heavy cream',1,'cup','Dairy'],['Vanilla extract',.5,'tsp','Pantry']],
 'Melt chocolate and butter, cool slightly and mix in yolks. Whip whites with cream of tartar and quarter-cup sugar; fold into chocolate. Whip half the cream with two tablespoons sugar and vanilla, then fold in. Portion and chill at least two hours; whip remaining cream with two teaspoons sugar for topping.',
 {sourceYield:'6 individual cups',minutes:140,prepMinutes:20,restMinutes:120,tags:['Vegetarian','Gluten-Free','Nut-Free'],vessel:'Mixer + six dessert glasses',makeAhead:'Make mousse one day ahead and keep refrigerated; top near serving.',seasoning:'Requires pasteurized eggs because the source uses uncooked eggs. Sugar total includes topping; optional chocolate shavings separate. Check chocolate labels for allergens.'}),
add('hot-cider','Maple + citrus spiced cider','Drink · Non-alcoholic',6,'Allrecipes',ar+'9501/hot-apple-cider/','4.8 ★ · 290 ratings',[
 ['Apple cider',6,'cup','Beverages'],['Maple syrup',.25,'cup','Pantry'],['Cinnamon sticks',2,'each','Pantry'],['Whole cloves',6,'each','Pantry'],['Allspice berries',6,'each','Pantry'],['Oranges',1,'each','Produce'],['Lemons',1,'each','Produce']],
 'Warm cider and maple syrup with spices and citrus peel tied in cheesecloth for 5–10 minutes. Do not boil. Remove the spice bundle and ladle into mugs.',
 {sourceYield:'6 one-cup mugs',minutes:15,prepMinutes:15,tags:['Vegan','Vegetarian','Gluten-Free','Dairy-Free','Egg-Free','Nut-Free'],kidFriendly:true,portion:'1 cup per guest',vessel:'Saucepan + cheesecloth + mugs',seasoning:'Buy citrus for peel only; reserve fruit for another use. Optional garnish sticks are extra.'}),
];
