import type { Dish } from './App';
// Ingredient amounts are normalized once, from the original recipe's base yield.
// Conservative end of publisher serving ranges is used; the range stays visible.
const recipe=(id:string,name:string,group:string,serves:number,sourceYield:string,url:string,ingredients:Dish['ingredients'],instructions:string,extra:Partial<Dish>={}):Dish=>({id,name,group,serves,sourceYield,style:'from-your-guide',minutes:0,oven:0,temp:0,cost:0,easyCost:0,portion:`${serves} base servings`,vessel:'Serving dish + utensil',easier:`Prepared ${name}`,makeAhead:'Prepare according to the source method.',finish:'Serve as specified in the source.',source:'Serious Eats',sourceUrl:url,recipeVerified:true,tags:[],seasoning:'Kosher salt and black pepper to taste; check pantry supplies.',ingredients:ingredients.map(([n,q,u,c])=>[n,q/serves,u,c]),instructions,...extra});
export const guideRecipes:Dish[]=[
recipe('turkey','Spatchcocked turkey + gravy','Main',10,'10–12 servings; one 12–14 lb bird','https://www.seriouseats.com/butterfiled-roast-turkey-with-gravy-recipe',[
['Turkey',1,'12–14 lb bird','Meat'],['Onions',3,'each','Produce'],['Carrots',3,'each','Produce'],['Celery',4,'stalk','Produce'],['Thyme',12,'sprig','Produce'],['Vegetable oil',2,'tbsp','Pantry'],['Stock',6,'cup','Pantry'],['Bay leaves',2,'each','Pantry'],['Butter',3,'tbsp','Dairy'],['Flour',4,'tbsp','Pantry']],
'Butterfly; reserve trimmings. Rack over two-thirds vegetables. Oil and season.\nRoast at 450°F, approximately 80 minutes; check breast 150°F, thigh 165°F.\nBrown trimmings and remaining vegetables; simmer with stock, thyme and bay 45 minutes. Strain.\nRoux butter and flour; add broth, reduce 20 minutes. Rest turkey 20 minutes; add juices.',{minutes:135,oven:80,temp:450,prepMinutes:10,restMinutes:20,batchMode:'whole',makeAhead:'Prepare the bird and reserved trimmings before roasting.',vessel:'Racked roasting tray + carving platter + gravy pitcher'}),
recipe('guide-breast','Herb-roasted turkey breast + stuffing','Main',6,'6–8 servings','https://www.seriouseats.com/roast-turkey-breast-stuffing-recipe',[
['Butter',8,'tbsp','Dairy'],['Sage sausage',1.5,'lb','Meat'],['Onions',1,'each','Produce'],['Celery',4,'stalk','Produce'],['Garlic',4,'clove','Produce'],['Sage',.25,'cup','Produce'],['Stock',4,'cup','Pantry'],['Eggs',3,'each','Dairy'],['Bread',2.5,'lb','Bakery'],['Parsley',.5,'cup','Produce'],['Oregano',2,'tbsp','Produce'],['Turkey breast',1,'4–5 lb breast','Meat']],
'Brown sausage in five tablespoons butter; soften vegetables. Add stock, eggs, parsley and dried bread.\nButter and herb the breast; place over dressing. Roast 450°F for 45 minutes.\nMove breast to rack; roast approximately 30 minutes to 145–150°F. Rest 20 minutes.\nReturn juices to dressing; bake 15 minutes to 160°F.',{minutes:155,oven:90,temp:450,prepMinutes:15,restMinutes:5,batchMode:'whole',ovenStages:[{label:'Roast breast over stuffing',minutes:45,temp:450},{label:'Move breast to rack; finish roasting',minutes:30,temp:450,restAfter:20},{label:'Reheat stuffing with juices',minutes:15,temp:450}],vessel:'9 × 13 inch baker + racked tray',makeAhead:'Dry the bread before assembling.'}),
recipe('stuffing','Sage and sausage dressing','Starch',10,'10–14 servings','https://www.seriouseats.com/classic-sage-and-sausage-stuffing-or-dressing-recipe',[
['Bread',2.5,'lb','Bakery'],['Butter',8,'tbsp','Dairy'],['Sage sausage',1.5,'lb','Meat'],['Onions',1,'each','Produce'],['Celery',4,'stalk','Produce'],['Garlic',2,'clove','Produce'],['Sage',.25,'cup','Produce'],['Stock',4,'cup','Pantry'],['Eggs',3,'each','Dairy'],['Parsley',.25,'cup','Produce']],
'Dry bread cubes at 275°F for 50 minutes; cool.\nBrown sausage in butter; soften vegetables. Combine with stock, eggs, parsley and bread.\nBake covered at 350°F for 45 minutes; uncover 15–20 minutes. Rest five minutes.',{minutes:170,oven:65,temp:350,prepMinutes:20,restMinutes:5,batchMode:'half',ingredientSteps:{Eggs:1},makeAhead:'Assemble and refrigerate one day before; allow one hour before baking.',vessel:'9 × 13 inch baking dish',ovenStages:[{label:'Dry bread',minutes:50,temp:275},{label:'Bake covered, then uncover',minutes:65,temp:350,waitBefore:20}]}),
recipe('greens','Homemade green bean casserole','Fresh',8,'8–12 servings','https://www.seriouseats.com/homemade-green-bean-casserole-recipe',[
['Shallots',1,'lb','Produce'],['Canola oil',2,'cup','Pantry'],['Mushrooms',1.5,'lb','Produce'],['Soy sauce',2,'tsp','Pantry'],['Lemon juice',2,'tsp','Produce'],['Stock',2,'cup','Pantry'],['Cream',1.5,'cup','Dairy'],['Butter',2,'tbsp','Dairy'],['Garlic',2,'clove','Produce'],['Flour',.25,'cup','Pantry'],['Green beans',2,'lb','Produce']],
'Fry shallots; drain and cool.\nBrown mushrooms in reserved oil and butter; add garlic, flour, liquids. Simmer.\nBlanch beans five minutes; ice-cool and drain. Combine sauce, beans and half shallots.\nBake 350°F for 15–20 minutes; finish with remaining shallots.',{minutes:100,oven:20,temp:350,prepMinutes:80,makeAhead:'Cold casserole: reheat 40 minutes at 350°F.',vessel:'9 × 13 inch casserole'}),
recipe('cranberry','Cranberry sauce','Sauce',8,'8–12 servings','https://www.seriouseats.com/the-food-lab-thanksgiving-special-the-worlds-easiest-cranberry-sauce',[
['Cranberries',12,'oz','Produce'],['Sugar',1,'cup','Pantry'],['Water',.5,'cup','Kitchen'],['Orange juice',2,'tbsp','Produce'],['Orange zest',2,'strip','Produce'],['Cinnamon stick',1,'each','Pantry']],
'Combine ingredients and a pinch of salt in a saucepan. Bring to a boil, then simmer, stirring and crushing berries, about ten minutes until jam-like.\nCool thirty minutes. Adjust consistency with water. Orange and cinnamon are optional.',{minutes:45,prepMinutes:15,restMinutes:30,makeAhead:'Refrigerate sealed up to one week before serving.',seasoning:'Pinch of kosher salt.',vessel:'Saucepan + small serving bowl'}),
recipe('potatoes','Ultra-fluffy mashed potatoes','Starch',4,'4–6 servings (the source also carries an inconsistent older yield label)','https://www.seriouseats.com/ultra-fluffy-mashed-potatoes-recipe',[
['Russet potatoes',2,'lb','Produce'],['Milk',.5,'cup','Dairy'],['Butter',6,'tbsp','Dairy']],
'Peel, cube and rinse potatoes until water clears. Cover with salted water; simmer until tender, about fifteen minutes after boiling.\nDrain, hot-rinse thirty seconds, steam-dry one minute, then rice. Gently fold in butter. Heat milk around potatoes and fold in; season.',{minutes:40,prepMinutes:40,makeAhead:'Finish near service; keep added milk flexible.',vessel:'Pot + ricer + serving bowl'}),
recipe('gravy','Basic turkey gravy','Sauce',12,'12 servings; 3 cups','https://www.seriouseats.com/basic-turkey-gravy-thanksgiving-recipe',[
['Butter',.25,'cup','Dairy'],['Flour',.25,'cup','Pantry'],['Stock',4,'cup','Pantry']],
'Melt butter; whisk in flour and cook about two minutes. Gradually add stock or drippings.\nBoil, then simmer ten to fifteen minutes until reduced to three cups. Season and serve, or refrigerate and reheat gently.',{minutes:25,prepMinutes:25,makeAhead:'Refrigerate in a sealed container; reheat before dinner.',vessel:'Saucepan + gravy pitcher'}),
recipe('salad','Shaved Brussels salad with hazelnuts + goat cheese','Fresh',4,'4–6 servings','https://www.seriouseats.com/salt-wilted-brussels-sprout-salad-recipe-8746808',[
['Brussels sprouts',1.75,'lb','Produce'],['Kosher salt',2,'tsp','Pantry'],['Tangerine',1,'each','Produce'],['Shallots',.5,'each','Produce'],['Dijon mustard',1,'tsp','Pantry'],['White wine vinegar',2,'tbsp','Pantry'],['Olive oil',6,'tbsp','Pantry'],['Hazelnuts',.75,'cup','Pantry'],['Goat cheese',4,'oz','Dairy']],
'Salt-knead half the shredded sprouts, add tangerine juice; chill fifteen minutes.\nWhisk shallot, mustard, vinegar, zest and oil. Toast hazelnuts four minutes; crush.\nSqueeze wilted sprouts dry. Toss with raw sprouts, nuts and dressing; fold in cheese.',{minutes:30,prepMinutes:30,makeAhead:'Wilted sprouts may chill up to four hours.',tags:['Vegetarian'],vessel:'Mandoline + skillet + wide bowl'}),
recipe('pie','Extra-smooth pumpkin pie','Dessert',8,'8–10 servings; one 9 inch pie','https://www.seriouseats.com/extra-smooth-pumpkin-pie-recipe',[
['Pie dough',1,'9 inch crust','Bakery'],['Sugar',6,'oz','Pantry'],['Kosher salt',.5,'tsp','Pantry'],['Cinnamon',1,'tsp','Pantry'],['Ground ginger',1,'tsp','Pantry'],['Nutmeg',.5,'tsp','Pantry'],['Cream cheese',8,'oz','Dairy'],['Pumpkin purée',15,'oz','Pantry'],['Butter',4,'tbsp','Dairy'],['Eggs',3,'each','Dairy']],
'Line a nine-inch plate with dough. Blind-bake at 425°F: fifteen minutes weighted, ten without. Cool.\nBlend sugar, spices, cream cheese, pumpkin, butter, then eggs until smooth; strain.\nFill crust; bake 350°F for 30–35 minutes. Cool at least one hour.',{easier:'Bakery pumpkin pie',minutes:240,oven:60,temp:350,prepMinutes:60,restMinutes:60,batchMode:'whole',seasoning:'The measured salt and spices are included above.',makeAhead:'Bake and chill up to two days before.',vessel:'9 inch pie plate + processor + strainer',ovenStages:[{label:'Blind-bake crust',minutes:25,temp:425},{label:'Bake filling',minutes:35,temp:350,waitBefore:60}]}),
recipe('guide-roast-sprouts','Roasted Brussels sprouts','Fresh',4,'4–6 servings','https://www.seriouseats.com/easy-roasted-brussels-sprouts-food-lab-recipe',[
['Brussels sprouts',1.5,'lb','Produce'],['Olive oil',3,'tbsp','Pantry']],
'Preheat a lined sheet pan on the upper-third rack at 500°F. Halve sprouts, oil and season.\nPlace cut-side-down on the hot pan. Roast about twenty minutes until tender and deeply browned; serve.',{minutes:25,oven:20,temp:500,prepMinutes:5,vessel:'Rimmed sheet pan + platter',makeAhead:'Trim and halve ahead; roast near service.'}),
recipe('sweet','Roasted sweet potatoes','Starch',6,'6–8 servings','https://www.seriouseats.com/the-best-roasted-sweet-potatoes-thanksgiving-sides-the-food-lab-recipe',[
['Sweet potatoes',3,'lb','Produce'],['Olive oil',6,'tbsp','Pantry'],['Parsley',2,'tbsp','Produce'],['Honey',1,'tbsp','Pantry']],
'Cut potatoes into half-inch slices. Cover with water at 160°F; cover and set aside one hour.\nDrain; toss with half the oil and seasoning. Roast 400°F for thirty minutes, flip, then twenty more.\nToss with remaining oil, parsley and honey.',{minutes:120,oven:50,temp:400,prepMinutes:65,vessel:'Two sheet pans + platter',makeAhead:'Plan the one-hour warm-water stage before roasting.'}),

recipe('guide-apple','BA’s Best Apple Pie','Dessert',8,'8 servings; one deep-dish pie','https://www.bonappetit.com/recipe/best-apple-pie',[
['Flour',3.5,'cup','Pantry'],['Sugar',.375,'cup','Pantry'],['Kosher salt',2,'tsp','Pantry'],['Butter',1.625,'cup','Dairy'],['Apple cider vinegar',2,'tbsp','Pantry'],['Apples',4,'lb','Produce'],['Brown sugar',1/3,'cup','Pantry'],['Lemon juice',2,'tbsp','Produce'],['Cinnamon',2,'tsp','Pantry'],['Allspice',.25,'tsp','Pantry'],['Cardamom',.25,'tsp','Pantry'],['Apple cider',1.5,'cup','Beverages'],['Vanilla bean',1,'each','Pantry'],['Cornstarch',2,'tbsp','Pantry'],['Eggs',1,'each','Dairy']],
'Combine dough; chill two hours. Macerate seasoned apples one hour.\nReduce cider and apple juices; thicken with cornstarch. Fill, seal and egg-wash pastry.\nBake 375°F for 90–120 minutes; cool four hours.',{source:'Bon Appétit',minutes:180,prepMinutes:180,oven:120,temp:375,restMinutes:240,batchMode:'whole',seasoning:'Flour and demerara for finishing; cold water as required by source.',makeAhead:'Bake the day before.',vessel:'9 inch deep pie dish'}),
recipe('guide-sweet-mash','Brown-butter mashed sweet potatoes','Starch',8,'8–10 servings; 6 cups','https://www.seriouseats.com/the-best-mashed-sweet-potatoes-recipe',[
['Sweet potatoes',4,'lb','Produce'],['Thyme',8,'sprig','Produce'],['Butter',6,'tbsp','Dairy'],['Maple syrup',.25,'cup','Pantry'],['Kosher salt',.5,'tsp','Pantry']],
'Foil-wrap potatoes with six thyme sprigs; start in a cold oven set to 300°F. Roast 90–105 minutes.\nUnwrap; roast 400°F for thirty minutes. Cool twenty minutes.\nBrown butter; add syrup and remaining thyme. Peel and beat potatoes into butter mixture; season.',{minutes:165,oven:135,temp:400,prepMinutes:15,restMinutes:20,seasoning:'Diamond Crystal salt measured above.',makeAhead:'Can be prepared ahead and reheated.',vessel:'Sheet pan + mixer',ovenStages:[{label:'Slow roast in foil',minutes:105,temp:300},{label:'Finish roasting',minutes:30,temp:400}]}),
recipe('guide-gratin','Rich and silky potato gratin','Starch',6,'6 as a side; source also lists 8 servings','https://www.seriouseats.com/classic-potato-gratin-recipe',[
['Cream',2,'cup','Dairy'],['Milk',1,'cup','Dairy'],['Garlic',2,'clove','Produce'],['Shallots',2,'each','Produce'],['Nutmeg',.125,'tsp','Pantry'],['Thyme',6,'sprig','Produce'],['Black peppercorns',2,'tsp','Pantry'],['Kosher salt',1.5,'tsp','Pantry'],['Russet potatoes',1.75,'lb','Produce'],['Parmesan',2,'oz','Dairy'],['Gruyère',4,'oz','Dairy'],['Butter',1,'tbsp','Dairy']],
'Boil dairy and aromatics; steep one hour. Reboil and strain. Slice potatoes into hot dairy.\nLayer in buttered dish with half the cheese. Bake covered 350°F sixty minutes; add remaining cheese, uncover twenty minutes. Rest thirty minutes.',{minutes:190,oven:80,temp:350,prepMinutes:70,restMinutes:30,seasoning:'Measured seasoning is included above.',vessel:'2 quart baking dish',makeAhead:'Steep the dairy before assembling.'}),
recipe('guide-mushroom','Vegetarian mushroom pot pie','Main',6,'6 servings','https://www.seriouseats.com/vegetarian-mushroom-pot-pie-recipe-11847075',[
['Mushrooms',1.5,'lb','Produce'],['Vegetable oil',3,'tbsp','Pantry'],['Water',2.5,'cup','Kitchen'],['Dried porcini',.5,'oz','Pantry'],['Butter',.25,'cup','Dairy'],['Pearl onions',1,'cup','Frozen'],['Carrots',2,'each','Produce'],['Parsnips',1,'each','Produce'],['Thyme',1,'tbsp','Produce'],['White miso',1,'tbsp','Pantry'],['Oregano',2,'tsp','Pantry'],['Kosher salt',2,'tsp','Pantry'],['Black pepper',1,'tsp','Pantry'],['Flour',.25,'cup','Pantry'],['Milk',1.5,'cup','Dairy'],['Puff pastry',1,'9.5 × 9 inch sheet','Frozen'],['Eggs',1,'each','Dairy']],
'Roast oiled mushrooms twenty minutes at 425°F. Simmer porcini and stems; blend.\nSauté vegetables; add seasonings, flour, broth and milk. Fold in mushrooms.\nTop with vented, egg-washed pastry; bake 425°F twenty-five minutes. Rest five minutes.',{minutes:90,oven:45,temp:425,prepMinutes:20,restMinutes:5,seasoning:'Extra flour for rolling; a teaspoon of water for egg wash.',makeAhead:'Make filling ahead; reheat before adding pastry.',vessel:'10 inch skillet + two sheet pans',tags:['Vegetarian'],ovenStages:[{label:'Roast mushrooms',minutes:20,temp:425},{label:'Bake assembled pie',minutes:25,temp:425,waitBefore:20}]}),
];
