import "./styles.css";
import {createPartyState} from "./domain/state.js";
import {derivePlan} from "./domain/planning.js";
import {browserStorage,loadState,saveState,backupState,restoreBackup} from "./domain/persistence.js";
import {generatePrintableBundle,markPrintableGenerated,printableStatus,renderPrintableHtml} from "./domain/printables.js";
import {addRecipeToMenu,removeDishFromMenu,requiredServingsForDish} from "./domain/recipes.js";
import {setDishPreparationMode} from "./domain/menu.js";
import {setPantryQuantity,recordPurchase} from "./domain/shopping.js";
import {assignSeat,unassignPerson} from "./domain/seating.js";

const storage=browserStorage();
let state=(storage&&loadState(storage))||createPartyState();
let active="home";
let saveLabel=storage?"Saved locally":"Local save unavailable";

const NAV=[
 ["home","HOME"],["party","PARTY PLAN"],["menu","MENU"],["prep","PREP"],["shopping","SHOPPING"],["table","TABLE"],
 ["space","SPACE + SEATING"],["timeline","TIMELINE"],["guests","GUESTS"],["experience","EXPERIENCE"],["budget","BUDGET"],["printables","PRINTABLES"]
];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
const qty=q=>q?`${fmt(q.quantity)} ${esc(q.unit||"")}`:"—";
const csv=v=>String(v||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);
const shoppingInventoryKey=key=>String(key||"").replace(/^(equipment|table|activity):/,"");
const localInput=v=>v?String(v).slice(0,16):"";
const app=document.querySelector("#app");

function persist(next,{bumpRevision=true}={}){
 if(!storage){state=next;saveLabel="Local save unavailable";render();return;}
 const result=saveState(storage,next,{expectedRevision:state.revision,bumpRevision});
 if(result.ok){state=result.state;saveLabel="Saved locally";}else{state=result.current;saveLabel="Save conflict — reloaded latest";}
 render();
}
function update(mutator,options){persist(mutator(structuredClone(state)),options);}

function issueList(p){
 const issues=[];
 for(const role of p.menu.missing)issues.push(`Menu missing: ${role.replace(/-/g," ")}`);
 for(const gap of p.dietaryCoverage.gaps.slice(0,4))issues.push(`${gap.name}: ${gap.status} ${gap.role} option`);
 if(p.table.seatShortage)issues.push(`${p.table.seatShortage} dining seats still needed`);
 if(p.table.chairShortage)issues.push(`${p.table.chairShortage} chairs still needed`);
 if(p.table.highChairShortage)issues.push(`${p.table.highChairShortage} high chairs still needed`);
 for(const zone of p.service.missingZones)issues.push(`Set up a ${zone.replace(/-/g," ")} zone`);
 if(p.timeline.issues.length)issues.push(`${p.timeline.issues.length} timeline conflict${p.timeline.issues.length===1?"":"s"}`);
 const buy=p.shopping.filter(x=>(x.remainingCanonical??0)>0).length;if(buy)issues.push(`${buy} shopping item${buy===1?"":"s"} still needed`);
 return issues;
}
function pageHeader(title,sub=""){return `<header class="pagehead"><div><p class="eyebrow">CROW & CROWN / THANKSGIVING</p><h1>${esc(title)}</h1></div>${sub?`<p class="page-sub">${esc(sub)}</p>`:""}</header>`;}
function stat(label,value,detail=""){return `<div class="stat"><span>${esc(label)}</span><strong>${esc(value)}</strong>${detail?`<small>${esc(detail)}</small>`:""}</div>`;}
function empty(text){return `<p class="empty">${esc(text)}</p>`;}

function setupView(){
 return `<main class="setup-shell"><div class="setup-card"><p class="eyebrow">CROW & CROWN / THANKSGIVING</p><h1>Thanksgiving,<br>already figured out.</h1><p class="page-sub">Set the few facts that drive the plan. You can change all of them later.</p><form id="setup-form" class="form-grid"><label>Planning for<input name="headcount" type="number" min="1" value="${state.planning.estimatedHeadcount||12}" required></label><label>Dinner time<input name="dinnerAt" type="datetime-local" value="${localInput(state.event.dinnerAt)}"></label><label>Service style<select name="service"><option value="family">Family style</option><option value="buffet">Buffet</option><option value="plated">Plated</option><option value="cocktail">Cocktail / grazing</option></select></label><label>Budget<input name="budget" type="number" min="0" value="${state.event.budget||0}"></label><label>Ovens<input name="ovens" type="number" min="0" value="${state.event.ovens??1}"></label><label>Burners<input name="burners" type="number" min="0" value="${state.event.burners??4}"></label><button class="primary" type="submit">Build my plan</button></form></div></main>`;
}

function homeView(p){
 const issues=issueList(p);
 return pageHeader("Thanksgiving, already figured out.","One plan. Every change recalculates what depends on it.")+
 `<section class="metric-strip">${stat("Planning for",String(p.planning.planningHeadcount),"people")}${stat("Dinner",state.event.dinnerAt?new Date(state.event.dinnerAt).toLocaleString():"Set a time")}${stat("Budget",state.event.budget?`$${fmt(state.event.budget)}`:"Set budget")}${stat("Service",p.service.style.label)}</section>
 <section class="two-col"><div class="panel"><div class="section-title"><span>NEEDS ATTENTION</span><strong>${issues.length}</strong></div>${issues.length?`<ul class="issue-list">${issues.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:empty("No current exceptions.")}</div>
 <div class="panel"><div class="section-title"><span>CONNECTED PLAN</span></div><dl class="compact-list"><div><dt>Menu roles</dt><dd>${p.menu.present.length} resolved</dd></div><div><dt>Shopping</dt><dd>${p.shopping.filter(x=>(x.remainingCanonical??0)>0).length} open</dd></div><div><dt>Prep</dt><dd>${p.prep.length} tasks</dd></div><div><dt>Seats</dt><dd>${p.table.seatCapacity}/${p.table.requiredSeats}</dd></div><div><dt>Timeline</dt><dd>${p.timeline.tasks.length} scheduled</dd></div></dl></div></section>`;
}
function partyView(p){return pageHeader("Party plan","Edit the event facts once; every dependent section uses them.")+
 `<form class="form-grid" id="party-form"><label>Planning mode<select name="mode"><option value="estimated" ${state.planning.mode==="estimated"?"selected":""}>Estimated</option><option value="expected" ${state.planning.mode==="expected"?"selected":""}>Expected guests</option><option value="confirmed" ${state.planning.mode==="confirmed"?"selected":""}>Confirmed guests</option><option value="custom" ${state.planning.mode==="custom"?"selected":""}>Custom</option></select></label><label>Planning headcount<input name="headcount" type="number" min="0" value="${p.planning.planningHeadcount}"></label><label>Dinner time<input name="dinnerAt" type="datetime-local" value="${localInput(state.event.dinnerAt)}"></label><label>Service style<select name="service">${Object.entries({family:"Family style",buffet:"Buffet",plated:"Plated",cocktail:"Cocktail / grazing"}).map(([v,l])=>`<option value="${v}" ${state.event.service===v?"selected":""}>${l}</option>`).join("")}</select></label><label>Budget<input name="budget" type="number" min="0" value="${state.event.budget||0}"></label><label>Ovens<input name="ovens" type="number" min="0" value="${state.event.ovens??1}"></label><label>Burners<input name="burners" type="number" min="0" value="${state.event.burners??4}"></label><label>Cooking helpers<input name="helpers" type="number" min="0" value="${state.event.cookingHelpers||0}"></label><label>Food buffer %<input name="foodBuffer" type="number" min="0" value="${state.planning.foodBufferPercent||0}"></label><label>Place-setting spare %<input name="spare" type="number" min="0" value="${state.planning.placeSettingSparePercent||0}"></label><button class="primary" type="submit">Update plan</button></form>`;}
function menuView(p){
 const rows=Object.entries(state.dishes||{}).filter(([,d])=>d?.on).map(([id,d])=>({id,d,recipe:state.recipes?.[d.recipeId||id]})).filter(x=>x.recipe);
 return pageHeader("Menu","Add a recipe once; ingredients, shopping, prep, equipment and timing recalculate from it.")+
 `<div class="section-title"><span>CURRENT MENU</span><strong>${rows.length}</strong></div>${rows.length?`<div class="rows">${rows.map(({id,d,recipe:r})=>`<div class="row menu-row"><div><strong>${esc(r.title)}</strong><span>${esc(r.mealRole||"uncategorized")} · plan ${fmt(requiredServingsForDish(state,id))} servings</span></div><div class="inline-actions"><select data-dish-mode="${esc(id)}"><option value="homemade" ${d.preparationMode==="homemade"?"selected":""}>Homemade</option><option value="purchased" ${d.preparationMode==="purchased"?"selected":""}>Purchased</option><option value="guest-provided" ${d.preparationMode==="guest-provided"?"selected":""}>Guest provided</option></select>${d.preparationMode==="guest-provided"?`<select data-contribution-status="${esc(id)}"><option value="pending" ${state.menuResponsibilities?.[id]?.status==="pending"||!state.menuResponsibilities?.[id]?"selected":""}>Contribution pending</option><option value="confirmed" ${state.menuResponsibilities?.[id]?.status==="confirmed"?"selected":""}>Contribution confirmed</option><option value="arrived" ${state.menuResponsibilities?.[id]?.status==="arrived"?"selected":""}>Dish arrived</option></select>`:""}<button class="text-button" data-action="remove-dish" data-id="${esc(id)}">Remove</button></div></div>`).join("")}</div>`:empty("No recipes selected yet. Add a custom recipe below; curated content can be loaded later.")}<div class="panel slim"><b>Missing roles:</b> ${p.menu.missing.length?p.menu.missing.map(x=>esc(x)).join(", "):"None"}</div>
 <form id="recipe-form" class="form-grid compact"><label>Recipe title<input name="title" required></label><label>Meal role<select name="role"><option value="main">Main</option><option value="secondary-main">Secondary main</option><option value="starch">Starch</option><option value="vegetable">Vegetable</option><option value="fresh">Salad / fresh</option><option value="bread">Bread</option><option value="sauce-condiment">Sauce / condiment</option><option value="appetizer">Appetizer</option><option value="dessert">Dessert</option><option value="non-alcoholic-drink">Non-alcoholic drink</option></select></label><label>Original servings<input name="servings" type="number" min="1" value="8" required></label><label>Portion logic<select name="basis"><option value="headcount">All planned guests</option><option value="role-share">Share this meal role</option><option value="adults">Adults only</option><option value="fixed">Fixed yield</option></select></label><label class="span-2">Ingredients — one per line: quantity | unit | ingredient<textarea name="ingredients" rows="5" placeholder="2 | cup | butter&#10;5 | lb | potatoes"></textarea></label><label class="span-2">Tasks — one per line: title | minutes | phase<textarea name="tasks" rows="5" placeholder="Peel potatoes | 20 | prep&#10;Boil potatoes | 25 | cook"></textarea></label><button class="primary" type="submit">Add to menu</button></form>`;
}
function spaceView(p){
 const byPerson=new Map(p.seating.namedPeople.map(x=>[x.personId,x]));
 return pageHeader("Space + seating","Assign each named guest once. Projected unnamed guests remain visible as placeholders.")+`<section class="metric-strip">${stat("Seats",`${p.seating.availableSeatCount}/${p.table.requiredSeats}`)}${stat("Unassigned named",String(p.seating.unassigned.length))}${stat("Planning placeholders",String(p.seating.placeholderCount))}${stat("Layout",p.space.measurementStatus)}</section>
 <form id="room-form" class="form-grid compact"><label>Room width in<input name="width" type="number" min="0" value="${state.room?.widthIn||0}"></label><label>Room length in<input name="length" type="number" min="0" value="${state.room?.lengthIn||0}"></label><button class="primary" type="submit">Update room</button></form>
 <div class="section-title"><span>SEATS</span><strong>${p.seating.seatIds.length}</strong></div>${p.seating.seatIds.length?`<div class="rows">${p.seating.seatIds.map(seatId=>{const personId=p.seating.assignments[seatId],person=byPerson.get(personId);return `<div class="row"><div><strong>${esc(seatId)}</strong><span>${person?esc(person.name):"Open"}</span></div><div class="inline-actions">${person?`<button class="text-button" data-action="unassign-seat" data-person="${esc(personId)}">Unassign</button>`:`<select data-seat-select="${esc(seatId)}"><option value="">Assign guest…</option>${p.seating.unassigned.map(x=>`<option value="${esc(x.personId)}">${esc(x.name)}</option>`).join("")}</select>`}</div></div>`;}).join("")}</div>`:empty("Add dining tables before assigning seats.")}
 <div class="two-col top-gap"><div class="panel"><div class="section-title"><span>ZONES</span></div>${p.space.zones.map(z=>`<div class="micro-row"><span>${esc(z.label||z.id)}</span><b>${esc(z.status||"defined")}</b></div>`).join("")||empty("No zones yet.")}</div><div class="panel"><div class="section-title"><span>SPACE ISSUES</span></div>${p.space.issues.length?p.space.issues.map(x=>`<div class="micro-row"><span>${esc(x.type)}</span><b>${esc((x.ids||[x.id]).filter(Boolean).join(", "))}</b></div>`).join(""):empty("No measured-space conflicts.")}</div></div>`;
}
function bind(){
 app.querySelector("#setup-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);persist({...state,setupCompleted:true,event:{...state.event,service:f.get("service"),budget:Number(f.get("budget"))||0,dinnerAt:f.get("dinnerAt")||null,ovens:Math.max(0,Number(f.get("ovens"))||0),burners:Math.max(0,Number(f.get("burners"))||0)},planning:{...state.planning,mode:"estimated",estimatedHeadcount:Math.max(1,Number(f.get("headcount"))||1)}});});
 app.querySelectorAll("[data-nav]").forEach(b=>b.addEventListener("click",()=>{active=b.dataset.nav;render();}));
 app.querySelector("#party-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),mode=String(f.get("mode")),headcount=Math.max(0,Number(f.get("headcount"))||0);update(x=>({...x,event:{...x.event,service:f.get("service"),budget:Number(f.get("budget"))||0,dinnerAt:f.get("dinnerAt")||null,ovens:Math.max(0,Number(f.get("ovens"))||0),burners:Math.max(0,Number(f.get("burners"))||0),cookingHelpers:Math.max(0,Number(f.get("helpers"))||0)},planning:{...x.planning,mode,[mode==="custom"?"customHeadcount":"estimatedHeadcount"]:headcount,foodBufferPercent:Math.max(0,Number(f.get("foodBuffer"))||0),placeSettingSparePercent:Math.max(0,Number(f.get("spare"))||0)}}));});
 app.querySelector("#recipe-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=`custom-${crypto.randomUUID()}`,ingredients=String(f.get("ingredients")||"").split(/\n+/).map(line=>line.split("|").map(x=>x.trim())).filter(parts=>parts[2]).map(([quantity,unit,name])=>({name,quantity:Number(quantity)||0,unit:unit||"each"})),tasks=String(f.get("tasks")||"").split(/\n+/).map(line=>line.split("|").map(x=>x.trim())).filter(parts=>parts[0]).map(([title,minutes,phase])=>({title,durationMinutes:Number(minutes)||0,phase:phase||"prep"}));update(x=>addRecipeToMenu(x,{id,title:String(f.get("title")),mealRole:String(f.get("role")),baseServings:Math.max(1,Number(f.get("servings"))||1),servingStrategy:{basis:String(f.get("basis"))},ingredients,prepTasks:tasks,metadataReviewed:false,allergenReviewed:false}));});
 app.querySelectorAll("[data-dish-mode]").forEach(el=>el.addEventListener("change",()=>update(x=>{let next=setDishPreparationMode(x,el.dataset.dishMode,el.value);if(el.value!=="guest-provided"){const responsibilities={...(next.menuResponsibilities||{})};delete responsibilities[el.dataset.dishMode];next={...next,menuResponsibilities:responsibilities};}return next;})));\n app.querySelectorAll("[data-contribution-status]").forEach(el=>el.addEventListener("change",()=>update(x=>({...x,menuResponsibilities:{...(x.menuResponsibilities||{}),[el.dataset.contributionStatus]:{ownerType:"guest",status:el.value}}}))));
 app.querySelectorAll('[data-action="remove-dish"]').forEach(b=>b.addEventListener("click",()=>update(x=>removeDishFromMenu(x,b.dataset.id))));
 app.querySelectorAll(".shopping-line").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(form),key=form.dataset.shoppingKey,kind=form.dataset.kind,row=derivePlan(state).shopping.find(x=>x.key===key),unit=row?.required?.unit||row?.unit||"each",have=Math.max(0,Number(f.get("have"))||0),purchased=Math.max(0,Number(f.get("purchased"))||0),cost=Math.max(0,Number(f.get("cost"))||0);update(x=>{let next=x;if(kind==="ingredient"||kind==="manual")next=setPantryQuantity(next,key,have,unit);else if(kind!=="prepared-food"){if(key.startsWith("table:linen:")&&row?.requirement){const id=`shopping-${key}`,linens=(next.inventory?.linens||[]).filter(item=>item.id!==id);if(have>0){const req=row.requirement;linens.push(req.shape==="round"?{id,shape:"round",diameterIn:req.diameterIn,quantity:Math.ceil(have)}:{id,shape:"rectangle",lengthIn:req.lengthIn,widthIn:req.widthIn,quantity:Math.ceil(have)});}next={...next,inventory:{...(next.inventory||{}),linens}};}else{const invKey=shoppingInventoryKey(key);next={...next,inventory:{...(next.inventory||{}),[invKey]:{quantity:have}}};}}return recordPurchase(next,key,purchased,unit,cost);});}));
 app.querySelector("#manual-shopping-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(x=>({...x,manualShoppingItems:[...(x.manualShoppingItems||[]),{id:crypto.randomUUID(),name:String(f.get("name")),quantity:Math.max(0,Number(f.get("quantity"))||0),unit:String(f.get("unit")||"each")}]}));});
 app.querySelector("#inventory-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(x=>({...x,inventory:{...(x.inventory||{}),chairs:{quantity:Number(f.get("chairs"))||0},"high-chairs":{quantity:Number(f.get("highchairs"))||0},"dinner-plates":{quantity:Number(f.get("plates"))||0},"dessert-plates":{quantity:Number(f.get("dessert"))||0},forks:{quantity:Number(f.get("forks"))||0},knives:{quantity:Number(f.get("knives"))||0},glasses:{quantity:Number(f.get("glasses"))||0},napkins:{quantity:Number(f.get("napkins"))||0}}}));});
 app.querySelector("#table-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=String(f.get("id")||`table-${state.tables.length+1}`);update(x=>({...x,tables:[...x.tables,{id,use:String(f.get("use")||"dining"),shape:f.get("shape"),seatCapacity:Number(f.get("seats"))||0,lengthIn:Number(f.get("length"))||0,widthIn:Number(f.get("width"))||0,diameterIn:Number(f.get("diameter"))||0,linenDropIn:Number(f.get("drop"))||0}]}));});
 app.querySelectorAll('[data-action="remove-table"]').forEach(b=>b.addEventListener("click",()=>update(x=>({...x,tables:x.tables.filter(t=>String(t.id)!==b.dataset.id)}))));
 app.querySelector("#room-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(x=>({...x,room:{...x.room,widthIn:Number(f.get("width"))||0,lengthIn:Number(f.get("length"))||0}}));});
 app.querySelectorAll("[data-seat-select]").forEach(el=>el.addEventListener("change",()=>{if(el.value)update(x=>assignSeat(x,el.value,el.dataset.seatSelect));}));
 app.querySelectorAll('[data-action="unassign-seat"]').forEach(b=>b.addEventListener("click",()=>update(x=>unassignPerson(x,b.dataset.person))));
 app.querySelectorAll("[data-task-form]").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(form),id=form.dataset.taskForm;update(x=>({...x,taskOverrides:{...(x.taskOverrides||{}),[id]:{...(x.taskOverrides?.[id]||{}),durationMinutes:Math.max(0,Number(f.get("duration"))||0),fixedStart:f.get("fixed")||null}}}));}));
 app.querySelector("#manual-task-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(x=>({...x,manualTasks:[...(x.manualTasks||[]),{id:`manual-${crypto.randomUUID()}`,title:String(f.get("title")),durationMinutes:Math.max(0,Number(f.get("duration"))||0),fixedStart:f.get("fixed")||null}]}));});
 app.querySelector("#guest-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(x=>({...x,guests:[...x.guests,{id:crypto.randomUUID(),name:String(f.get("name")),rsvp:f.get("rsvp"),type:f.get("type"),dietaryRestrictions:csv(f.get("dietary")),allergies:csv(f.get("allergies")),plus:Number(f.get("plus"))?1:0,plusDietaryRestrictions:csv(f.get("plusDietary")),plusAllergies:csv(f.get("plusAllergies")),kids:Math.max(0,Number(f.get("kids"))||0),highChairs:Math.max(0,Number(f.get("highchairs"))||0)}]}));});
 app.querySelectorAll("[data-guest-rsvp]").forEach(el=>el.addEventListener("change",()=>update(x=>{const guests=[...x.guests],i=Number(el.dataset.guestRsvp);guests[i]={...guests[i],rsvp:el.value};return {...x,guests};})));
 app.querySelectorAll('[data-action="remove-guest"]').forEach(b=>b.addEventListener("click",()=>update(x=>({...x,guests:x.guests.filter((_,i)=>i!==Number(b.dataset.index))}))));
 app.querySelectorAll('[data-action="toggle-activity"]').forEach(b=>b.addEventListener("click",()=>update(x=>{const selected={...(x.selectedActivities||{})};if(selected[b.dataset.id])delete selected[b.dataset.id];else selected[b.dataset.id]=true;return {...x,selectedActivities:selected};})));
 app.querySelector("#activity-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=`activity-${crypto.randomUUID()}`,supply=String(f.get("supply")||"").trim(),task=String(f.get("task")||"").trim();update(x=>({...x,activities:{...(x.activities||{}),[id]:{name:String(f.get("name")),supplies:supply?[{key:supply.toLowerCase().replace(/\s+/g,"-"),name:supply,quantityPerPerson:Math.max(0,Number(f.get("perPerson"))||0)}]:[],tasks:task?[{id:"setup",title:task,durationMinutes:Math.max(0,Number(f.get("minutes"))||0)}]:[],zoneRequirement:String(f.get("zone")||"").trim()||null,printables:[]}},selectedActivities:{...(x.selectedActivities||{}),[id]:true}}));});
 app.querySelectorAll('[data-action="print"]').forEach(b=>b.addEventListener("click",()=>{const bundle=generatePrintableBundle(state),item=bundle.printables[b.dataset.type];if(!item)return;const w=window.open("","_blank");if(w){w.document.write(renderPrintableHtml(item));w.document.close();w.focus();w.print();}update(x=>markPrintableGenerated(x,b.dataset.type),{bumpRevision:false});}));
 app.querySelector('[data-action="backup"]')?.addEventListener("click",()=>{const blob=new Blob([backupState(state)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="crow-crown-thanksgiving-backup.json";a.click();URL.revokeObjectURL(a.href);});
 app.querySelector("#restore-input")?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{persist(restoreBackup(await file.text()));}catch{saveLabel="Backup could not be restored";render();}});
 app.querySelector('[data-action="reset"]')?.addEventListener("click",()=>{if(confirm("Reset this event? Download a backup first if you want to keep it.")){storage?.removeItem?.("crow-crown-thanksgiving:event");state=createPartyState();saveLabel="Reset";render();}});
}
render();
