export type Printable={id?:string;name:string;desc:string};
export function printableFormat(card:Printable){const id=card.id||'';return id.startsWith('guest-')||id.startsWith('dish-')?{kind:'tent',width:3.5,height:4}:{kind:id==='kids'?'placemat':'sheet',width:id==='kids'?11:8.5,height:id==='kids'?8.5:11};}
const printStyles=`@font-face{font-family:Metropolis;src:url('/fonts/Metropolis-ExtraLight.otf');font-weight:200}@font-face{font-family:Lato;src:url('/fonts/Lato-Light.ttf');font-weight:300}@page{size:letter;margin:.3in}*{box-sizing:border-box}body{margin:0;background:white;color:#191919;font-family:Lato,Arial,sans-serif;font-weight:300}.print-sheet{break-after:page;padding:.4in;min-height:10in}.brand{font-size:10pt;letter-spacing:3pt;text-align:center}.card h1{font-family:Metropolis,Arial,sans-serif;font-weight:200;font-size:26pt;text-align:center;margin:.35in 0}.card p{white-space:pre-wrap;line-height:1.55;font-size:14pt;overflow-wrap:anywhere}.card{border:1px solid #bbb;padding:.35in;break-inside:avoid}.tent-page{display:flex;flex-wrap:wrap;align-content:start;gap:.15in;break-after:page}.tent{padding:0;width:3.5in;height:4in;border:1px dashed #888;position:relative;break-inside:avoid;overflow:hidden}.tent::after{content:'';position:absolute;top:50%;left:0;width:100%;border-top:1px dotted #777}.tent-face{height:2in;padding:.18in;text-align:center;overflow:hidden}.tent-face h1{font-size:17pt;margin:.2in 0 .08in}.tent-face p{font-size:9pt;line-height:1.25;margin:0}.tent-back{transform:rotate(180deg)}.placemat{min-height:7.5in}.placemat p{line-height:2.1}.activity-space{height:1.8in;border:1px dashed #aaa;margin-top:.2in}.print-hint{font-size:9pt;color:#444;text-align:center}@media print{.print-controls{display:none}}`;
function makeFace(doc:Document,card:Printable){const face=doc.createElement('div');face.className='tent-face';const brand=doc.createElement('div');brand.className='brand';brand.textContent='CROW & CROWN';const h=doc.createElement('h1');h.textContent=card.name.replace(/^(Food label|Bar sign) · /,'');const p=doc.createElement('p');p.textContent=card.desc;face.append(brand,h,p);return face;}
export function printDocument(doc:Document,cards:Printable[]){
 doc.open();doc.write('<!doctype html><html><head><title>Crow &amp; Crown · Thanksgiving printables</title><meta charset="utf-8"></head><body></body></html>');doc.close();const style=doc.createElement('style');style.textContent=printStyles;doc.head.append(style);
 const controls=doc.createElement('p');controls.className='print-controls';controls.textContent='Print at 100% scale. Fold tent cards on the dotted line. Use landscape when printing only a kids placemat.';doc.body.append(controls);
 let tents:HTMLElement|undefined,tentCount=0;
 for(const card of cards){const f=printableFormat(card);if(f.kind==='tent'){if(!tents||tentCount===4){tents=doc.createElement('section');tents.className='tent-page';doc.body.append(tents);tentCount=0;}const el=doc.createElement('article');el.className='card tent';const back=makeFace(doc,card);back.classList.add('tent-back');el.append(back,makeFace(doc,card));tents.append(el);tentCount++;}else{tents=undefined;const page=doc.createElement('section');page.className='print-sheet';const el=doc.createElement('article');el.className='card '+(f.kind==='placemat'?'placemat':'');const brand=doc.createElement('div');brand.className='brand';brand.textContent='CROW & CROWN';const h=doc.createElement('h1');h.textContent=card.name;const p=doc.createElement('p');p.textContent=card.desc;el.append(brand,h,p);if(f.kind==='placemat'){const draw=doc.createElement('div');draw.className='activity-space';draw.setAttribute('aria-label','Drawing space');el.append(draw);}page.append(el);doc.body.append(page);}}
 return doc;
}
export function printCards(cards:Printable[]){if(!cards.length)return;const frame=document.createElement('iframe');frame.title='Crow & Crown print preview';Object.assign(frame.style,{position:'fixed',width:'0',height:'0',border:'0'});document.body.append(frame);const doc=printDocument(frame.contentDocument!,cards);if(cards.length===1&&cards[0].id==='kids'){const landscape=doc.createElement('style');landscape.textContent='@page{size:letter landscape}.print-sheet{min-height:7.5in}';doc.head.append(landscape);}void Promise.all([doc.fonts.load('200 26px Metropolis'),doc.fonts.load('300 14px Lato')]).then(()=>{frame.contentWindow!.focus();frame.contentWindow!.print();setTimeout(()=>frame.remove(),60000);});}
// 300 pixels per printed inch. Text is drawn directly so no screenshot service sees the plan.
export async function downloadCardImage(card:Printable){await Promise.all([document.fonts.load('200 26px Metropolis'),document.fonts.load('300 14px Lato')]);const f=printableFormat(card),canvas=document.createElement('canvas');canvas.width=f.width*300;canvas.height=f.height*300;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#191919';ctx.textAlign='center';const wrap=(text:string,y:number,size:number,family:string,maxWidth:number)=>{ctx.font=`${family==='Metropolis'?200:300} ${size}px ${family}, sans-serif`;for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(' ')){const next=line?line+' '+word:word;if(ctx.measureText(next).width>maxWidth&&line){ctx.fillText(line,canvas.width/2,y);y+=size*1.4;line=word;}else line=next;}ctx.fillText(line,canvas.width/2,y);y+=size*1.4;}return y;};
 const draw=(top:number,height:number)=>{ctx.strokeStyle='#aaa';ctx.strokeRect(30,top+30,canvas.width-60,height-60);let y=wrap('CROW & CROWN',top+75,f.kind==='tent'?25:38,'Lato',canvas.width-100);y=wrap(card.name.replace(/^(Food label|Bar sign) · /,''),y+45,f.kind==='tent'?48:80,'Metropolis',canvas.width-110);wrap(card.desc,y+30,f.kind==='tent'?27:44,'Lato',canvas.width-110);};if(f.kind==='tent'){ctx.save();ctx.translate(canvas.width,canvas.height/2);ctx.rotate(Math.PI);draw(0,canvas.height/2);ctx.restore();draw(canvas.height/2,canvas.height/2);ctx.setLineDash([10,10]);ctx.beginPath();ctx.moveTo(0,canvas.height/2);ctx.lineTo(canvas.width,canvas.height/2);ctx.stroke();}else draw(0,canvas.height);
 canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`crow-crown-${(card.id||card.name).toLowerCase().replace(/[^a-z0-9-]/g,'-')}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');
}
